---
title: "set up"
author: "An Bui"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. libraries
```{r}
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
```

# 2. data
## a. biomass
```{r}
biomass <- read_csv(here::here("data", "LTE_All_Species_Biomass_at_transect_20200605.csv")) %>% 
  clean_names() %>% 
  # ANOB is incorrectly coded as having "SESSILE" mobility
  mutate(mobility = ifelse(sp_code == "ANOB", "MOBILE", mobility)) %>% 
  # create a sample_ID for each sampling date at each treatment at each site
  unite("sample_ID", site, treatment, date, remove = FALSE) %>% 
  # create "functional groups" of group and mobility
  unite("group_mobility", group, mobility, remove = FALSE, sep = "_") %>% 
  # change to lower case
  mutate_at(c("group", "mobility", "group_mobility", "growth_morph"), str_to_lower)
```

# 3. operators
```{r}
'%!in%' <- function(x,y)!('%in%'(x,y))
```

# 4. start and end dates
## a. Naples (NAPL)
```{r}
napl_start_dates <- c("NAPL_CONTROL_2008-01-10", "NAPL_ANNUAL_2008-01-10", "NAPL_CONTINUAL_2010-04-27")

napl_start_date <- as_date("2008-01-10")

napl_after_date <- as_date("2016-02-09")
```

## b. Mohawk (MOHK)
```{r}
mohk_start_dates <- c("MOHK_ANNUAL_2008-01-17", "MOHK_CONTROL_2008-01-17", "MOHK_CONTINUAL_2010-05-05")

mohk_start_date <- as_date("2008-01-17")

mohk_after_date <- as_date("2017-02-13")
```

## c. Arroyo Quemado (AQUE)
```{r}
aque_start_dates <- c("AQUE_CONTROL_2008-01-30", "AQUE_ANNUAL_2008-01-30", "AQUE_CONTINUAL_2010-04-26")

aque_start_date <- as_date("2008-01-30")

aque_after_date <- as_date("2017-03-02")
```

## d. Carpinteria (CARP)
```{r}
carp_start_dates <- c("CARP_CONTROL_2008-02-12", "CARP_ANNUAL_2008-02-12", "CARP_CONTINUAL_2010-04-23")

carp_start_date <- as_date("2008-02-12")

carp_after_date <- as_date("2017-02-15")
```

## e. Isla Vista (IVEE)
```{r}
ivee_start_dates <- c("IVEE_CONTROL_2011-10-26", "IVEE_ANNUAL_2011-10-26")

ivee_start_date <- as_date("2011-10-26")

ivee_after_date <- as_date("2016-02-18")
```

# 5. useful vectors
## a. species codes --> scientific name
```{r}
spp_names <- biomass %>% 
  select(group, sp_code, scientific_name, common_name) %>% 
  unique() 

spp_codes <- biomass %>% 
  pull(sp_code) %>% 
  unique()
```

```{r}
# algae
algae_spp <- spp_names %>% 
  filter(group == "ALGAE") %>% 
  pull(sp_code)

fish_spp <- spp_names %>% 
  filter(group == "FISH") %>% 
  pull(sp_code)

invert_spp <- spp_names %>% 
  filter(group == "INVERT") %>% 
  pull(sp_code)
```

## b. sites
```{r}
LTE_sites <- biomass %>% 
  pull(site) %>% 
  unique()
```

