---
title: "figure functions"
author: "An Bui"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("code", "00-set_up.Rmd"))
```

# 1. biomass timeseries

# a. function
```{r}
spp_biomass_ts <- function(spp_code, this_site) {
  
  start_dates <- if(this_site == "NAPL") {
    napl_start_dates
  } else if(this_site == "MOHK") {
    mohk_start_dates
  } else if(this_site == "AQUE") {
    aque_start_dates
  } else if(this_site == "CARP") {
    carp_start_dates
  } else if(this_site == "IVEE") {
    ivee_start_dates
  }
  
  end_dates <- if(this_site == "NAPL") {
    napl_after_date
  } else if (this_site == "MOHK") {
    mohk_after_date
  } else if(this_site == "AQUE") {
    aque_after_date
  } else if(this_site == "CARP") {
    carp_after_date
  } else if(this_site == "IVEE") {
    ivee_after_date
  }
  
  full_sci_name <- spp_names %>% filter(sp_code == spp_code) %>% pull(scientific_name)
  
  plot_label <- paste(full_sci_name, " - ", this_site, sep = "")
  
  biomass %>% 
    filter(sp_code == spp_code & site == this_site) %>% 
    # replace all -99999 values with NA
    mutate(dry_gm2 = replace(dry_gm2, dry_gm2 < 0, NA)) %>% 
    # calculate total dry mass by each survey
    group_by(year, month, treatment, date, sample_ID) %>% 
    summarize(total_biomass = sum(dry_gm2)) %>% 
    ungroup() %>% 
    # make a new column designating "start", "during" and "after" removal
    mutate(exp = case_when(sample_ID %in% start_dates ~ "start",
                           date > end_dates ~ "after",
                           TRUE ~ "during"),
           exp = factor(exp, levels = c("start", "during", "after"))) %>% 
    
    ggplot(., aes(x = date, y = total_biomass)) +
    geom_line(alpha = 0.5) +
    geom_point(aes(color = exp)) +
    labs(title = plot_label,
         x = "Year",
         y = "Total dry mass",
         color = "Experiment") +
    facet_wrap(~treatment) +
    theme_bw()
  
}

spp_biomass_ts("PTCA", "NAPL")
spp_biomass_ts("PTCA", "MOHK")
spp_biomass_ts("PTCA", "IVEE")
spp_biomass_ts("CYOS", "NAPL")
spp_biomass_ts("AB", "NAPL")
spp_biomass_ts("ANSP", "NAPL")

```















