---
title: "figure_outputs"
author: "An Bui"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r source-code}
source(here::here("code", "01a-figure_functions.R"))
```

# 1. biomass timeseries 

## a. species plots
```{r plot-list-outputs}
# algae
NAPL_algae_plot_list
MOHK_algae_plot_list
AQUE_algae_plot_list
CARP_algae_plot_list
IVEE_algae_plot_list

# fish
NAPL_fish_plot_list
MOHK_fish_plot_list
AQUE_fish_plot_list
CARP_fish_plot_list
IVEE_fish_plot_list

# inverts
NAPL_invert_plot_list
MOHK_invert_plot_list
AQUE_invert_plot_list
CARP_invert_plot_list
IVEE_invert_plot_list
```

## b. group plots
```{r}
# whole groups
NAPL_invert <- group_biomass("invert", "NAPL")
NAPL_algae <- group_biomass("algae", "NAPL")
NAPL_fish <- group_biomass("fish", "NAPL")

MOHK_invert <- group_biomass("invert", "MOHK")
MOHK_algae <- group_biomass("algae", "MOHK")
MOHK_fish <- group_biomass("fish", "MOHK")

CARP_invert <- group_biomass("invert", "CARP")
CARP_algae <- group_biomass("algae", "CARP")
CARP_fish <- group_biomass("fish", "CARP")

IVEE_invert <- group_biomass("invert", "IVEE")
IVEE_algae <- group_biomass("algae", "IVEE")
IVEE_fish <- group_biomass("fish", "IVEE")

AQUE_invert <- group_biomass("invert", "AQUE")
AQUE_algae <- group_biomass("algae", "AQUE")
AQUE_fish <- group_biomass("fish", "AQUE")

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-NAPL-invert.jpg"), NAPL_invert, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-NAPL-algae.jpg"), NAPL_algae, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-NAPL-fish.jpg"), NAPL_fish, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-MOHK-invert.jpg"), MOHK_invert, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-MOHK-algae.jpg"), MOHK_algae, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-MOHK-fish.jpg"), MOHK_fish, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-CARP-invert.jpg"), CARP_invert, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-CARP-algae.jpg"), CARP_algae, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-CARP-fish.jpg"), CARP_fish, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-IVEE-invert.jpg"), IVEE_invert, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-IVEE-algae.jpg"), IVEE_algae, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-IVEE-fish.jpg"), IVEE_fish, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-AQUE-invert.jpg"), AQUE_invert, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-AQUE-fish.jpg"), AQUE_fish, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-AQUE-algae.jpg"), AQUE_algae, width = 7, height = 3, dpi = 150)
```


