---
title: "change in biomass"
author: "An Bui"
date: "12/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("code", "00-set_up.R"))

library(nlme)
```

```{r}
delta_bio <- biomass %>% 
  # calculate total dry mass by each survey
  group_by(site, group_mobility, year, month, treatment, date) %>% 
  summarize(total_biomass = sum(dry_gm2)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  pivot_wider(names_from = treatment, values_from = total_biomass) %>% 
  mutate(delta_biomass = CONTROL - ANNUAL)

```

```{r}
group_mobility_biomass_plot_list <- rep(NaN, length(group_mobility))

for(i in 1:length(group_mobility)) {
  # choose a group
  this_group <- group_mobility[i]
  
  # run the function
  plot <- ggplot(delta_bio %>% filter(group_mobility == this_group), aes(x = date, y = delta_biomass)) +
    geom_line(alpha = 0.5) +
    geom_hline(yintercept = 0) +
    geom_point(aes(color = exp_dates), size = 2) +
    facet_wrap(~site)
  
  # put the plot name into a list
  group_mobility_biomass_plot_list[i] <- paste(this_group, "_biomass_plot", sep = "")
  
  # make a separate object for the plot
  assign(paste(this_group, "_biomass_plot", sep = ""), plot)
  
}

group_mobility_biomass_plot_list

invert_sessile_biomass_plot
fish_mobile_biomass_plot
invert_mobile_biomass_plot
algae_sessile_biomass_plot

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-delta-invert_sessile.jpg"), invert_sessile_biomass_plot, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-delta-fish.jpg"), fish_mobile_biomass_plot, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-delta-invert_mobile.jpg"), invert_mobile_biomass_plot, width = 7, height = 3, dpi = 150)

ggsave(here::here("figures/trajectories/biomass", "biomass_timeseries-delta-algae.jpg"), algae_sessile_biomass_plot, width = 7, height = 3, dpi = 150)
```

