---
title: "change in biomass"
author: "An Bui"
date: "12/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("data", "00-set_up.Rmd"))

library(nlme)
```

```{r}
delta_bio <- biomass %>% 
  unite("group_mobility", group, mobility, sep = "_", remove = FALSE) %>% 
  # filter(site == "MOHK" & group == "INVERT") %>% 
  mutate(dry_gm2 = replace(dry_gm2, dry_gm2 < 0, NA)) %>% 
  # calculate total dry mass by each survey
  group_by(site, group_mobility, year, month, treatment, date) %>% 
  summarize(total_biomass = sum(dry_gm2)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  pivot_wider(names_from = treatment, values_from = total_biomass) %>% 
  mutate(delta_biomass = CONTROL - ANNUAL)

ggplot(delta_bio %>% filter(group_mobility == "ALGAE_SESSILE"), aes(x = date, y = delta_biomass)) +
  geom_line(alpha = 0.5) +
  geom_point(aes(color = exp_dates), size = 2) +
  facet_wrap(~site)

ggplot(delta_bio %>% filter(group_mobility == "INVERT_MOBILE"), aes(x = date, y = delta_biomass)) +
  geom_line(alpha = 0.5) +
  geom_point(aes(color = exp_dates), size = 2) +
  facet_wrap(~site)

ggplot(delta_bio %>% filter(group_mobility == "INVERT_SESSILE"), aes(x = date, y = delta_biomass)) +
  geom_line(alpha = 0.5) +
  geom_point(aes(color = exp_dates), size = 2) +
  facet_wrap(~site)

ggplot(delta_bio %>% filter(group_mobility == "FISH_MOBILE"), aes(x = date, y = delta_biomass)) +
  geom_line(alpha = 0.5) +
  geom_point(aes(color = exp_dates), size = 2) +
  facet_wrap(~site)

```

