---
title: "understory algae"
author: "An Bui"
date: "5/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0. set up

```{r}
source(here::here("code", "00-set_up.R"))

```

# 1. algae deltas

```{r}
# total biomass
algae_biomass <- biomass %>% 
  filter(group == "algae" & sp_code != "MAPY") %>% 
  # # make a new column for after dates
  after_dates_column() %>% 
  # make a new column for during and after and set factor levels
  exp_dates_column()

# delta biomass
delta_algae_biomass <- algae_biomass %>% 
  dplyr::select(site, year, month, treatment, date, exp_dates, dry_gm2) %>% 
  group_by(site, exp_dates, year, month, treatment, date) %>% 
  summarize(total_dry = sum(dry_gm2)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = treatment, values_from = total_dry) %>% 
  mutate(delta_annual = annual - control,
         delta_continual = continual - control) 

delta_algae_annual <- delta_algae_biomass %>% 
  dplyr::select(site, year, month, date, control, annual, delta_annual) %>% 
  drop_na(delta_annual) %>% 
  mutate(exp_dates = case_when(
    # after for annual removal:
    site == "aque" & date >= aque_after_date_annual ~ "after",
    site == "napl" & date >= napl_after_date_annual ~ "after",
    site == "ivee" & date >= ivee_after_date_annual ~ "after",
    site == "mohk" & date >= mohk_after_date_annual ~ "after",
    site == "carp" & date >= carp_after_date_annual ~ "after",
    # everything else is "during" the experiment
    TRUE ~ "during"
  ),
  exp_dates = fct_relevel(exp_dates, c("during", "after"))) %>% 
   # create a column for quarter
  mutate(quarter = case_when(
    month <= 3 ~ "Q1",
    month <= 6 ~ "Q2",
    month <= 9 ~ "Q3",
    TRUE ~ "Q4"
  )) %>% 
  # calculate time since start of experiment
  mutate(time_yrs = case_when(
    # AQUE, NAPL, MOHK, CARP: control and annual started in 2008
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q1" ~ year + 0.125 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q2" ~ year + 0.375 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q3" ~ year + 0.625 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q4" ~ year + 0.875 - 2008, 
    # IVEE control and annual started in 2011
    site == "ivee" & quarter == "Q1" ~ year + 0.125 - 2011,
    site == "ivee" & quarter == "Q2" ~ year + 0.375 - 2011,
    site == "ivee" & quarter == "Q3" ~ year + 0.625 - 2011,
    site == "ivee" & quarter == "Q4" ~ year + 0.875 - 2011
    )) %>% 
  group_by(site) %>% 
  mutate(time_since_start = time_yrs - min(time_yrs)) %>% 
  ungroup() %>% 
  # calculate time since end of experiment
  group_by(site, exp_dates) %>% 
  # if "after", then simple: the time in years - the minimum time in years
  # if "during", then more complex: take the max time in years and add 0.25, then subtract the time in years
  mutate(time_since_end = case_when(
    exp_dates == "during" ~ -(max(time_yrs) + 0.25 - time_yrs),
    exp_dates == "after" ~ time_yrs - min(time_yrs)
  )) %>% 
  ungroup() %>% 
  left_join(., enframe(sites_full), by = c("site" = "name")) %>% 
  rename(site_full = value) %>% 
  mutate(site_full = fct_relevel(site_full, "Arroyo Quemado (AQUE)", "Naples (NAPL)", "Isla Vista (IVEE)", "Mohawk (MOHK)", "Carpinteria (CARP)")) %>% 
  # create a new column for "kelp year"
  mutate(quarter = fct_relevel(quarter, "Q2", "Q3", "Q4", "Q1")) %>% 
  mutate(kelp_year = case_when(
    quarter %in% c("Q2", "Q3", "Q4") ~ year,
    quarter == "Q1" ~ year - 1
  )) %>% 
  mutate(kelp_year = paste("kelp_", kelp_year, "-", kelp_year + 1, sep = "")) %>% 
  # create a column for the points to compare for "2 year interval"
  mutate(comp_2yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2008-2009", "kelp_2009-2010") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_2yrs = fct_relevel(comp_2yrs, "start", "during", "after")) %>% 
  # create a column for the points to compare for "3 year interval"
  mutate(comp_3yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2008-2009", "kelp_2009-2010", "kelp_2010-2011") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013", "kelp_2013-2014") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2019-2020", "kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_3yrs = fct_relevel(comp_3yrs, "start", "during", "after"))

delta_algae_continual <- delta_algae_biomass %>% 
  dplyr::select(site, year, month, date, control, continual, delta_continual) %>% 
  # take out years where continual removal hadn't happened yet
  drop_na(delta_continual) %>% 
  mutate(exp_dates = case_when(
    # after for annual removal:
    site == "aque" & date >= aque_after_date_continual ~ "after",
    site == "napl" & date >= napl_after_date_continual ~ "after",
    site == "mohk" & date >= mohk_after_date_continual ~ "after",
    site == "carp" & date >= carp_after_date_continual ~ "after",
    # everything else is "during" the experiment
    TRUE ~ "during"
  ),
  exp_dates = fct_relevel(exp_dates, c("during", "after"))) %>% 
  # create a column for quarter
  mutate(quarter = case_when(
    month <= 3 ~ "Q1",
    month <= 6 ~ "Q2",
    month <= 9 ~ "Q3",
    TRUE ~ "Q4"
  )) %>% 
  # calculate time since start of experiment
  mutate(time_yrs = case_when(
    # AQUE, NAPL, MOHK, CARP: continual started in 2010
    quarter == "Q1" ~ year + 0.125 - 2010,
    quarter == "Q2" ~ year + 0.375 - 2010,
    quarter == "Q3" ~ year + 0.625 - 2010,
    quarter == "Q4" ~ year + 0.875 - 2010
  )) %>% 
  group_by(site) %>% 
  mutate(time_since_start = time_yrs - min(time_yrs)) %>% 
  ungroup() %>% 
  # calculate time since end of experiment
  group_by(site, exp_dates) %>% 
  mutate(time_since_end = case_when(
    exp_dates == "during" ~ -(max(time_yrs) + 0.25 - time_yrs),
    exp_dates == "after" ~ time_yrs - min(time_yrs)
  )) %>% 
  ungroup() %>% 
  left_join(., enframe(sites_full), by = c("site" = "name")) %>% 
  rename(site_full = value) %>% 
  mutate(site_full = fct_relevel(site_full, "Arroyo Quemado (AQUE)", "Naples (NAPL)", "Mohawk (MOHK)", "Carpinteria (CARP)")) %>% 
  # create a new column for "kelp year"
  mutate(quarter = fct_relevel(quarter, "Q2", "Q3", "Q4", "Q1")) %>% 
  mutate(kelp_year = case_when(
    quarter %in% c("Q2", "Q3", "Q4") ~ year,
    quarter == "Q1" ~ year - 1
  )) %>% 
  mutate(kelp_year = paste("kelp_", kelp_year, "-", kelp_year + 1, sep = "")) %>% 
  # create a column for the points to compare for "2 year interval"
  mutate(comp_2yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2010-2011", "kelp_2011-2012") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_2yrs = fct_relevel(comp_2yrs, "start", "during", "after")) %>% 
  # create a column for the points to compare for "3 year interval"
  mutate(comp_3yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2010-2011", "kelp_2011-2012", "kelp_2012-2013") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013", "kelp_2013-2014") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2019-2020", "kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_3yrs = fct_relevel(comp_3yrs, "start", "during", "after")) %>% 
  # create a new sample ID that is site, year, quarter
  unite("sample_ID", site, year, quarter, remove = FALSE) %>% 
  rename("control_algae" = control,
         "continual_algae" = continual,
         "delta_continual_algae" = delta_continual) %>% 
  left_join(., delta_continual %>% dplyr::select(sample_ID, continual, control, delta_continual), by = "sample_ID")
```

# 2. algae

## a. annualized delta for site quality

```{r}
algae_annual_means <- delta_algae_annual %>% 
  group_by(site, kelp_year) %>% 
  mutate(mean_delta = mean(delta_annual), 
         mean_tse = mean(time_since_end),
         se_delta = se(delta_annual)) %>% 
  dplyr::select(site, site_full, kelp_year, mean_delta, mean_tse, exp_dates, se_delta) %>% 
  unique() %>% 
  full_join(., site_quality, by = "site")

algae_annual_after_means <- algae_annual_means %>% 
  filter(exp_dates == "after")

linear_model <- lm(mean_delta ~ mean_tse + quality + mean_tse*quality, data = algae_annual_after_means, na.action = na.pass)
dredge(linear_model) %>% 
  model.sel() %>% 
  gt()
linear_model_sel <- lm(mean_delta ~ mean_tse + quality + mean_tse*quality, data = algae_annual_after_means, na.action = na.pass)
summary(linear_model_sel)
plot(simulateResiduals(linear_model_sel))
# ggeffects
predicted <- ggpredict(linear_model_sel, terms = ~ mean_tse + quality + mean_tse*quality, type = "fixed") %>% 
  rename("quality" = group) 
# emmeans
grid <- ref_grid(linear_model_sel, cov.keep = c("mean_tse", "quality"))
emm <- emmeans(grid, spec = c("mean_tse", "quality"), level = 0.95) %>% 
  data.frame(.)

annual_algae_sitequality_ggpredict <- ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  # raw data: means and error bars
  # facet_wrap(~quality, nrow = 1) +
  geom_point(data = algae_annual_means, aes(x = mean_tse, y = mean_delta, color = exp_dates, shape = site)) +
  # geom_errorbar(data = algae_annual_means, aes(x = mean_tse, y = mean_delta, ymin = mean_delta - se_delta, ymax = mean_delta + se_delta, color = exp_dates)) +
  scale_color_manual(values = c("during" = "grey", "after" = "black"), guide = "none") +
  # predicted values
  geom_ribbon(data = predicted, aes(x = x, y = predicted, ymin = conf.low, ymax = conf.high, fill = quality), alpha = 0.5, show.legend = FALSE) +
  geom_line(data = predicted, aes(x = x, y = predicted)) +
  # theme
  theme_bw() + 
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size = 18),
        axis.text = element_text(size = 10),
        strip.text = element_text(size = 10)) +
  labs(x = "Time since end of experiment", y = "\U0394 biomass (treatment - control)",
       title = "Understory algal biomass",
       caption = "ggpredict")

annual_algae_sitequality_emmeans <- ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  facet_wrap(~quality, nrow = 1) +
  geom_point(data = algae_annual_means, aes(x = mean_tse, y = mean_delta, color = exp_dates, shape = site)) +
  scale_color_manual(values = c("during" = "grey", "after" = "black"), guide = "none") +
  # predicted values
  geom_ribbon(data = emm, aes(x = mean_tse, y = emmean, ymin = lower.CL, ymax = upper.CL, fill = quality), alpha = 0.5, show.legend = FALSE) +
  geom_line(data = emm, aes(x = mean_tse, y = emmean, col = quality)) +
  theme_bw() + 
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size = 18),
        axis.text = element_text(size = 10),
        strip.text = element_text(size = 10)) +
  labs(x = "Time since end of experiment", y = "\U0394 biomass (treatment - control)",
       title = "\U0394 annual - annualized data", 
       subtitle = "understory algal biomass", 
       caption = "emmeans")
```

## b. delta algae vs delta kelp
```{r}
cor.test(delta_algae_continual$delta_continual_algae, delta_algae_continual$delta_continual,
         method = "pearson")

delta_algae_vs_kelp <- lm(delta_continual_algae ~ delta_continual, data = delta_algae_continual)
summary(delta_algae_vs_kelp)

delta_algae_vs_kelp_lme <- lme(delta_continual_algae ~ delta_continual, 
                               random = ~ 1|year/site, 
                               data = delta_algae_continual, na.action = na.pass)
summary(delta_algae_vs_kelp_lme)

delta_algae_vs_kelp_lmer <- lmer(delta_continual_algae ~ delta_continual + (1|year) + (1|site), 
                                data = delta_algae_continual)
summary(delta_algae_vs_kelp_lmer)
plot(simulateResiduals(delta_algae_vs_kelp_lmer))
MuMIn::r.squaredGLMM(delta_algae_vs_kelp_lmer)

predicted_delta_algae_vs_kelp <- ggpredict(delta_algae_vs_kelp_lmer, terms = ~ delta_continual, type = "fixed")

delta_algae_continual %>% 
  ggplot(aes(x = delta_continual, y = delta_continual_algae)) +
  geom_hline(aes(yintercept = 0), lty = 2, color = "grey") +
  geom_vline(aes(xintercept = 0), lty = 2, color = "grey") +
  # geom_point(aes(col = comp_3yrs)) +
  # new_scale("color") +
  # stat_summary(aes(group = comp_3yrs), fun = mean, geom = "point", size = 10) +
  # geom_text(aes(label = date)) +
  geom_segment(aes(x = delta_continual, y = delta_continual_algae, 
                   xend = c(tail(delta_continual, n = -1), NA), 
                   yend = c(tail(delta_continual_algae, n = -1), NA), 
                   group = site, color = time_since_end), 
               arrow = arrow(length = unit(0.3, "cm")),
               size = 1) +
  scale_color_gradient2(low = "red", mid = "lightgrey", high = "blue") +
  labs(x = "\U0394 kelp biomass (treatment - control)",
       y = "\U0394 understory algae biomass (treatment - control)") +
  theme_bw() + 
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 14),
        strip.background = element_rect(fill = "#FFFFFF")) +
  facet_wrap(~site, scale = "free")

algae_vs_kelp <- delta_algae_continual %>% 
  ggplot(aes(x = delta_continual, y = delta_continual_algae)) +
  geom_hline(aes(yintercept = 0), lty = 3, color = "grey") +
  geom_vline(aes(xintercept = 0), lty = 3, color = "grey") +
  geom_point(aes(shape = exp_dates, fill = exp_dates), size = 5, shape = 21) + 
  geom_line(data = predicted_delta_algae_vs_kelp, aes(x = x, y = predicted), size = 2) +
  scale_linetype_manual(values = c("during" = 2, "after" = 1)) +
  scale_fill_manual(values = c("during" = "#FFFFFF", after = under_col)) +
  scale_x_continuous(breaks = seq(-2000, 2000, by = 1000), minor_breaks = seq(-2000, 2000, by = 500)) +
  labs(x = "\U0394 kelp biomass (treatment - control)",
       y = "\U0394 understory algae biomass (treatment - control)",
       caption = "marginal R2 = 0.028, conditional R2 = 0.519") +
  theme_bw() + 
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 14),
        legend.position = c(0.9, 0.9),
        legend.text = element_text(size = 18),
        legend.title = element_blank())
```

## c. delta algae as a function of time since end of experiment
```{r}
algae_continual_after <- delta_algae_continual %>% 
  filter(exp_dates == "after")

linear_model_algae_lme <- lme(delta_continual_algae ~ time_since_end, random = ~ 1|site, data = algae_continual_after, na.action = na.pass)
summary(linear_model_algae_lme)

linear_model_algae_lmer <- lmer(delta_continual_algae ~ time_since_end + (1|site), data = algae_continual_after, na.action = na.pass)
plot(simulateResiduals(linear_model_algae_lmer))

linear_model_algae_lmer_during <- lmer(delta_continual_algae ~ time_since_end + (1|site), data = delta_algae_continual %>% filter(exp_dates == "during"), na.action = na.pass)
# ggeffects
predicted_algae_after <- ggpredict(linear_model_algae_lmer, terms = ~ time_since_end, type = "fixed")
predicted_algae_during <- ggpredict(linear_model_algae_lmer_during, terms = ~ time_since_end, type = "fixed")

algae_time <- ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  geom_point(data = delta_algae_continual, 
             aes(x = time_since_end, y = delta_continual_algae, fill = site, shape = site), size = 3, alpha = 0.9) +
  scale_shape_manual(values = shape_palette_site) +
  scale_fill_manual(values = color_palette_site) +
  # new_scale("color") + 
  # overall
  geom_line(data = predicted_algae_after, aes(x = x, y = predicted), size = 2, alpha = 0.7) +
  geom_ribbon(data = predicted_algae_after, aes(x = x, ymax = conf.high, ymin = conf.low), alpha = 0.2) +
  geom_line(data = predicted_algae_during, aes(x = x, y = predicted), size = 2, alpha = 0.7) +
  geom_ribbon(data = predicted_algae_during, aes(x = x, ymax = conf.high, ymin = conf.low), alpha = 0.2) +
  scale_x_continuous(breaks = seq(-8, 5, by = 1), minor_breaks = NULL) +
  # scale_y_continuous(breaks = seq(-250, 750, by = 250), limits = c(-250, 750)) +
  theme_bw() + 
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 18),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14), 
        legend.position = c(0.08, 0.75), 
        plot.margin = margin(0, 0, 0, 0)) +
  labs(x = "Time since end of experiment", y = "\U0394 understory algal biomass")
```

```{r}
delta_algae_continual %>% 
  drop_na(comp_2yrs) %>% 
  ggplot(aes(x = comp_2yrs, y = delta_continual_algae)) +
  geom_boxplot() +
  geom_jitter() 
```


# 3. sessile invert deltas

```{r}
# total biomass
invert_biomass <- biomass %>% 
  filter(group == "invert" & mobility == "sessile") %>% 
  # take out piddocks?
  filter(taxon_family != "Pholadidae") %>% 
  # make a new column for after dates
  after_dates_column() %>% 
  # make a new column for during and after and set factor levels
  exp_dates_column()

# delta biomass
delta_invert_biomass <- invert_biomass %>% 
  dplyr::select(site, year, month, treatment, date, exp_dates, dry_gm2) %>% 
  group_by(site, exp_dates, year, month, treatment, date) %>% 
  summarize(total_dry = sum(dry_gm2)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = treatment, values_from = total_dry) %>% 
  mutate(delta_annual = annual - control,
         delta_continual = continual - control) 

delta_invert_annual <- delta_invert_biomass %>% 
  dplyr::select(site, year, month, date, control, annual, delta_annual) %>% 
  drop_na(delta_annual) %>% 
  mutate(exp_dates = case_when(
    # after for annual removal:
    site == "aque" & date >= aque_after_date_annual ~ "after",
    site == "napl" & date >= napl_after_date_annual ~ "after",
    site == "ivee" & date >= ivee_after_date_annual ~ "after",
    site == "mohk" & date >= mohk_after_date_annual ~ "after",
    site == "carp" & date >= carp_after_date_annual ~ "after",
    # everything else is "during" the experiment
    TRUE ~ "during"
  ),
  exp_dates = fct_relevel(exp_dates, c("during", "after"))) %>% 
   # create a column for quarter
  mutate(quarter = case_when(
    month <= 3 ~ "Q1",
    month <= 6 ~ "Q2",
    month <= 9 ~ "Q3",
    TRUE ~ "Q4"
  )) %>% 
  # calculate time since start of experiment
  mutate(time_yrs = case_when(
    # AQUE, NAPL, MOHK, CARP: control and annual started in 2008
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q1" ~ year + 0.125 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q2" ~ year + 0.375 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q3" ~ year + 0.625 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q4" ~ year + 0.875 - 2008, 
    # IVEE control and annual started in 2011
    site == "ivee" & quarter == "Q1" ~ year + 0.125 - 2011,
    site == "ivee" & quarter == "Q2" ~ year + 0.375 - 2011,
    site == "ivee" & quarter == "Q3" ~ year + 0.625 - 2011,
    site == "ivee" & quarter == "Q4" ~ year + 0.875 - 2011
    )) %>% 
  group_by(site) %>% 
  mutate(time_since_start = time_yrs - min(time_yrs)) %>% 
  ungroup() %>% 
  # calculate time since end of experiment
  group_by(site, exp_dates) %>% 
  # if "after", then simple: the time in years - the minimum time in years
  # if "during", then more complex: take the max time in years and add 0.25, then subtract the time in years
  mutate(time_since_end = case_when(
    exp_dates == "during" ~ -(max(time_yrs) + 0.25 - time_yrs),
    exp_dates == "after" ~ time_yrs - min(time_yrs)
  )) %>% 
  ungroup() %>% 
  left_join(., enframe(sites_full), by = c("site" = "name")) %>% 
  rename(site_full = value) %>% 
  mutate(site_full = fct_relevel(site_full, "Arroyo Quemado (AQUE)", "Naples (NAPL)", "Isla Vista (IVEE)", "Mohawk (MOHK)", "Carpinteria (CARP)")) %>% 
  # create a new column for "kelp year"
  mutate(quarter = fct_relevel(quarter, "Q2", "Q3", "Q4", "Q1")) %>% 
  mutate(kelp_year = case_when(
    quarter %in% c("Q2", "Q3", "Q4") ~ year,
    quarter == "Q1" ~ year - 1
  )) %>% 
  mutate(kelp_year = paste("kelp_", kelp_year, "-", kelp_year + 1, sep = "")) %>% 
  # create a column for the points to compare for "2 year interval"
  mutate(comp_2yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2008-2009", "kelp_2009-2010") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_2yrs = fct_relevel(comp_2yrs, "start", "during", "after")) %>% 
  # create a column for the points to compare for "3 year interval"
  mutate(comp_3yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2008-2009", "kelp_2009-2010", "kelp_2010-2011") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013", "kelp_2013-2014") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2019-2020", "kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_3yrs = fct_relevel(comp_3yrs, "start", "during", "after"))

delta_invert_continual <- delta_invert_biomass %>% 
  dplyr::select(site, year, month, date, control, continual, delta_continual) %>% 
  # take out years where continual removal hadn't happened yet
  drop_na(delta_continual) %>% 
  mutate(exp_dates = case_when(
    # after for annual removal:
    site == "aque" & date >= aque_after_date_continual ~ "after",
    site == "napl" & date >= napl_after_date_continual ~ "after",
    site == "mohk" & date >= mohk_after_date_continual ~ "after",
    site == "carp" & date >= carp_after_date_continual ~ "after",
    # everything else is "during" the experiment
    TRUE ~ "during"
  ),
  exp_dates = fct_relevel(exp_dates, c("during", "after"))) %>% 
  # create a column for quarter
  mutate(quarter = case_when(
    month <= 3 ~ "Q1",
    month <= 6 ~ "Q2",
    month <= 9 ~ "Q3",
    TRUE ~ "Q4"
  )) %>% 
  # calculate time since start of experiment
  mutate(time_yrs = case_when(
    # AQUE, NAPL, MOHK, CARP: continual started in 2010
    quarter == "Q1" ~ year + 0.125 - 2010,
    quarter == "Q2" ~ year + 0.375 - 2010,
    quarter == "Q3" ~ year + 0.625 - 2010,
    quarter == "Q4" ~ year + 0.875 - 2010
  )) %>% 
  group_by(site) %>% 
  mutate(time_since_start = time_yrs - min(time_yrs)) %>% 
  ungroup() %>% 
  # calculate time since end of experiment
  group_by(site, exp_dates) %>% 
  mutate(time_since_end = case_when(
    exp_dates == "during" ~ -(max(time_yrs) + 0.25 - time_yrs),
    exp_dates == "after" ~ time_yrs - min(time_yrs)
  )) %>% 
  ungroup() %>% 
  left_join(., enframe(sites_full), by = c("site" = "name")) %>% 
  rename(site_full = value) %>% 
  mutate(site_full = fct_relevel(site_full, "Arroyo Quemado (AQUE)", "Naples (NAPL)", "Mohawk (MOHK)", "Carpinteria (CARP)")) %>% 
  # create a new column for "kelp year"
  mutate(quarter = fct_relevel(quarter, "Q2", "Q3", "Q4", "Q1")) %>% 
  mutate(kelp_year = case_when(
    quarter %in% c("Q2", "Q3", "Q4") ~ year,
    quarter == "Q1" ~ year - 1
  )) %>% 
  mutate(kelp_year = paste("kelp_", kelp_year, "-", kelp_year + 1, sep = "")) %>% 
  # create a column for the points to compare for "2 year interval"
  mutate(comp_2yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2010-2011", "kelp_2011-2012") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_2yrs = fct_relevel(comp_2yrs, "start", "during", "after")) %>% 
  # create a column for the points to compare for "3 year interval"
  mutate(comp_3yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2010-2011", "kelp_2011-2012", "kelp_2012-2013") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013", "kelp_2013-2014") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2019-2020", "kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_3yrs = fct_relevel(comp_3yrs, "start", "during", "after")) %>% 
  # create a new sample ID that is site, year, quarter
  unite("sample_ID", site, year, quarter, remove = FALSE) %>% 
  rename("control_inverts" = control,
         "continual_inverts" = continual,
         "delta_continual_inverts" = delta_continual) %>% 
  left_join(., delta_continual %>% dplyr::select(sample_ID, continual, control, delta_continual), by = "sample_ID")
```

# 4. inverts

## a. annualized data for inverts

```{r}
invert_annual_means <- delta_invert_annual %>% 
  group_by(site, kelp_year) %>% 
  mutate(mean_delta = mean(delta_annual), 
         mean_tse = mean(time_since_end),
         se_delta = se(delta_annual)) %>% 
  dplyr::select(site, site_full, kelp_year, mean_delta, mean_tse, exp_dates, se_delta) %>% 
  unique() %>% 
  full_join(., site_quality, by = "site")

invert_annual_after_means <- invert_annual_means %>% 
  filter(exp_dates == "after")

linear_model <- lm(mean_delta ~ mean_tse + quality + mean_tse*quality, data = invert_annual_after_means, na.action = na.pass)
dredge(linear_model) %>% 
  model.sel() %>% 
  gt()
linear_model_sel <- lm(mean_delta ~ mean_tse + quality + mean_tse*quality, data = invert_annual_after_means, na.action = na.pass)
summary(linear_model_sel)
plot(simulateResiduals(linear_model_sel))
# ggeffects
predicted <- ggpredict(linear_model_sel, terms = ~ mean_tse + quality + mean_tse*quality, type = "fixed") %>% 
  rename("quality" = group) 
# emmeans
grid <- ref_grid(linear_model_sel, cov.keep = c("mean_tse", "quality"))
emm <- emmeans(grid, spec = c("mean_tse", "quality"), level = 0.95) %>% 
  data.frame(.)

annual_invert_sitequality_ggpredict <- ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  # raw data: means and error bars
  # facet_wrap(~quality, nrow = 1) +
  geom_point(data = invert_annual_means, aes(x = mean_tse, y = mean_delta, color = exp_dates, shape = site)) +
  # geom_smooth(data = invert_annual_means, aes(x = mean_tse, y = mean_delta, color = exp_dates), method = "lm") +
  # geom_errorbar(data = algae_annual_means, aes(x = mean_tse, y = mean_delta, ymin = mean_delta - se_delta, ymax = mean_delta + se_delta, color = exp_dates)) +
  scale_color_manual(values = c("during" = "grey", "after" = "black"), guide = "none") +
  # predicted values
  geom_ribbon(data = predicted, aes(x = x, y = predicted, ymin = conf.low, ymax = conf.high, fill = quality), alpha = 0.5, show.legend = FALSE) +
  geom_line(data = predicted, aes(x = x, y = predicted)) +
  facet_wrap(~quality) +
  # theme
  theme_bw() + 
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size = 18),
        axis.text = element_text(size = 10),
        strip.text = element_text(size = 10)) +
  labs(x = "Time since end of experiment", y = "\U0394 biomass (treatment - control)",
       title = "Sessile invert biomass",
       caption = "ggpredict")

annual_algae_sitequality_emmeans <- ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  facet_wrap(~quality, nrow = 1) +
  geom_point(data = invert_annual_means, aes(x = mean_tse, y = mean_delta, color = exp_dates, shape = site)) +
  scale_color_manual(values = c("during" = "grey", "after" = "black"), guide = "none") +
  # predicted values
  geom_ribbon(data = emm, aes(x = mean_tse, y = emmean, ymin = lower.CL, ymax = upper.CL, fill = quality), alpha = 0.5, show.legend = FALSE) +
  geom_line(data = emm, aes(x = mean_tse, y = emmean, col = quality)) +
  theme_bw() + 
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size = 18),
        axis.text = element_text(size = 10),
        strip.text = element_text(size = 10)) +
  labs(x = "Time since end of experiment", y = "\U0394 biomass (treatment - control)",
       title = "\U0394 annual - annualized data", 
       subtitle = "sessile invert biomass", 
       caption = "emmeans")
```

```{r}
plots_together <- (annual_kelp_sitequality_ggpredict / annual_algae_sitequality_ggpredict / annual_invert_sitequality_ggpredict) +
  plot_layout(guides = "collect")
plots_together
```

## b. delta inverts vs delta kelp

```{r}
cor.test(delta_invert_continual$delta_continual_inverts, delta_invert_continual$delta_continual,
         method = "pearson")

delta_invert_vs_kelp <- lm(delta_continual_inverts ~ delta_continual, data = delta_invert_continual)
summary(delta_invert_vs_kelp)

delta_invert_vs_kelp_lme <- lme(delta_continual_inverts ~ delta_continual, 
                               random = ~ 1|year/site, 
                               data = delta_invert_continual, na.action = na.pass)
summary(delta_invert_vs_kelp_lme)

delta_invert_vs_kelp_lmer <- lmer(delta_continual_inverts ~ delta_continual + (1|year) + (1|site), 
                                data = delta_invert_continual)
summary(delta_invert_vs_kelp_lmer)
plot(simulateResiduals(delta_invert_vs_kelp_lmer))
MuMIn::r.squaredGLMM(delta_invert_vs_kelp_lmer)

predicted_delta_invert_vs_kelp <- ggpredict(delta_invert_vs_kelp_lmer, terms = ~ delta_continual, type = "fixed")

delta_invert_continual %>% 
  ggplot(aes(x = delta_continual, y = delta_continual_inverts)) +
  geom_hline(aes(yintercept = 0), lty = 2, color = "grey") +
  geom_vline(aes(xintercept = 0), lty = 2, color = "grey") +
  # geom_point(aes(col = comp_3yrs)) +
  # new_scale("color") +
  # stat_summary(aes(group = comp_3yrs), fun = mean, geom = "point", size = 10) +
  # geom_text(aes(label = date)) +
  geom_segment(aes(x = delta_continual, y = delta_continual_inverts, 
                   xend = c(tail(delta_continual, n = -1), NA), 
                   yend = c(tail(delta_continual_inverts, n = -1), NA), 
                   group = site, color = time_since_end), 
               arrow = arrow(length = unit(0.3, "cm")),
               size = 1) +
  scale_color_gradient2(low = "red", mid = "lightgrey", high = "blue") +
  labs(x = "\U0394 kelp biomass (treatment - control)",
       y = "\U0394 invert biomass (treatment - control)") +
  theme_bw() + 
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 14),
        strip.background = element_rect(fill = "#FFFFFF")) +
  facet_wrap(~site, scale = "free")

inverts_vs_kelp <- delta_invert_continual %>% 
  ggplot(aes(x = delta_continual, y = delta_continual_inverts)) +
  geom_hline(aes(yintercept = 0), lty = 3, color = "grey") +
  geom_vline(aes(xintercept = 0), lty = 3, color = "grey") +
  geom_point(aes(shape = exp_dates, fill = exp_dates), size = 5, shape = 24) + 
  geom_line(data = predicted_delta_invert_vs_kelp, aes(x = x, y = predicted), size = 2) +
  scale_linetype_manual(values = c("during" = 2, "after" = 1)) +
  scale_fill_manual(values = c("during" = "#FFFFFF", after = carp_col)) +
  scale_x_continuous(breaks = seq(-2000, 2000, by = 1000), minor_breaks = seq(-2000, 2000, by = 500)) +
  labs(x = "\U0394 kelp biomass (treatment - control)",
       y = "\U0394 understory invert biomass (treatment - control)",
       caption = "marginal R2 = 0.043, conditional R2 = 0.391") +
  theme_bw() + 
  theme(axis.text = element_text(size = 14),
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 14),
        legend.position = c(0.9, 0.9),
        legend.text = element_text(size = 18),
        legend.title = element_blank())

```

## c. delta inverts

```{r}
invert_continual_after <- delta_invert_continual %>% 
  filter(exp_dates == "after")

linear_model_invert_lme <- lme(delta_continual_inverts ~ time_since_end, random = ~ 1|site, data = invert_continual_after, na.action = na.pass)
summary(linear_model_invert_lme)
# no effect of time since end

linear_model_invert_lmer <- lmer(delta_continual_inverts ~ time_since_end + (1|site), data = invert_continual_after, na.action = na.pass)
summary(linear_model_invert_lmer)
plot(simulateResiduals(linear_model_invert_lmer))

linear_model_invert_lmer_during <- lmer(delta_continual_inverts ~ time_since_end + (1|site), data = delta_invert_continual %>% filter(exp_dates == "during"), na.action = na.pass)
# ggeffects
predicted_invert_after <- ggpredict(linear_model_invert_lmer, terms = ~ time_since_end, type = "fixed")
predicted_invert_during <- ggpredict(linear_model_invert_lmer_during, terms = ~ time_since_end, type = "fixed")

invert_time <- ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  geom_point(data = delta_invert_continual, 
             aes(x = time_since_end, y = delta_continual_inverts, fill = site, shape = site), size = 3, alpha = 0.9) +
  scale_shape_manual(values = shape_palette_site) +
  scale_fill_manual(values = color_palette_site) +
  # new_scale("color") + 
  # overall
  geom_line(data = predicted_invert_after, aes(x = x, y = predicted), size = 2, alpha = 0.7) +
  geom_ribbon(data = predicted_invert_after, aes(x = x, ymax = conf.high, ymin = conf.low), alpha = 0.2) +
  geom_line(data = predicted_invert_during, aes(x = x, y = predicted), size = 2, alpha = 0.7) +
  geom_ribbon(data = predicted_invert_during, aes(x = x, ymax = conf.high, ymin = conf.low), alpha = 0.2) +
  scale_x_continuous(breaks = seq(-8, 5, by = 1), minor_breaks = NULL) +
  # scale_y_continuous(breaks = seq(-250, 750, by = 250), limits = c(-250, 750)) +
  theme_bw() + 
  theme(axis.title = element_text(size = 16),
        plot.title = element_text(size = 18),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14), 
        legend.position = "none", 
        plot.margin = margin(0, 0, 0, 0)) +
  labs(x = "Time since end of experiment", y = "\U0394 sessile invertebrate biomass")
```


## d. plots together

### class vs kelp
```{r}
plots_together <- algae_vs_kelp + inverts_vs_kelp
plots_together
ggsave(here::here("figures", paste("delta_vs_kelp-one_slope-", todays_date, ".jpg", sep = "")), 
       plot = plots_together, 
       height = 8, width = 16, dpi = 150)
```


### algae and inverts

```{r}
plots_together <- algae_time/invert_time &
  plot_annotation(tag_levels = "A")

plots_together
ggsave(here::here("figures", paste("algae_invert_time", todays_date, ".jpg", sep = "")), 
       plot = plots_together, 
       height = 8, width = 10, dpi = 150)
```


# 5. annualized data for algae species from rank abundance


```{r}
# total biomass
algae_spp_biomass <- biomass %>% 
  filter(sp_code %in% c("PTCA", "CO", "CC", "EGME", "CYOS", "DL", "R")) %>% 
  # # make a new column for after dates
  after_dates_column() %>% 
  # make a new column for during and after and set factor levels
  exp_dates_column()

# delta biomass
delta_algae_spp_biomass <- algae_spp_biomass %>% 
  dplyr::select(site, year, month, treatment, date, exp_dates, sp_code, dry_gm2) %>% 
  group_by(site, exp_dates, year, month, treatment, date, sp_code) %>% 
  summarize(total_dry = sum(dry_gm2)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = treatment, values_from = total_dry) %>% 
  mutate(delta_annual = annual - control,
         delta_continual = continual - control) 

delta_algae_spp_annual <- delta_algae_spp_biomass %>% 
  dplyr::select(site, year, month, date, sp_code, control, annual, delta_annual) %>% 
  drop_na(delta_annual) %>% 
  mutate(exp_dates = case_when(
    # after for annual removal:
    site == "aque" & date >= aque_after_date_annual ~ "after",
    site == "napl" & date >= napl_after_date_annual ~ "after",
    site == "ivee" & date >= ivee_after_date_annual ~ "after",
    site == "mohk" & date >= mohk_after_date_annual ~ "after",
    site == "carp" & date >= carp_after_date_annual ~ "after",
    # everything else is "during" the experiment
    TRUE ~ "during"
  ),
  exp_dates = fct_relevel(exp_dates, c("during", "after"))) %>% 
   # create a column for quarter
  mutate(quarter = case_when(
    month <= 3 ~ "Q1",
    month <= 6 ~ "Q2",
    month <= 9 ~ "Q3",
    TRUE ~ "Q4"
  )) %>% 
  # calculate time since start of experiment
  mutate(time_yrs = case_when(
    # AQUE, NAPL, MOHK, CARP: control and annual started in 2008
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q1" ~ year + 0.125 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q2" ~ year + 0.375 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q3" ~ year + 0.625 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q4" ~ year + 0.875 - 2008, 
    # IVEE control and annual started in 2011
    site == "ivee" & quarter == "Q1" ~ year + 0.125 - 2011,
    site == "ivee" & quarter == "Q2" ~ year + 0.375 - 2011,
    site == "ivee" & quarter == "Q3" ~ year + 0.625 - 2011,
    site == "ivee" & quarter == "Q4" ~ year + 0.875 - 2011
    )) %>% 
  group_by(site) %>% 
  mutate(time_since_start = time_yrs - min(time_yrs)) %>% 
  ungroup() %>% 
  # calculate time since end of experiment
  group_by(site, exp_dates) %>% 
  # if "after", then simple: the time in years - the minimum time in years
  # if "during", then more complex: take the max time in years and add 0.25, then subtract the time in years
  mutate(time_since_end = case_when(
    exp_dates == "during" ~ -(max(time_yrs) + 0.25 - time_yrs),
    exp_dates == "after" ~ time_yrs - min(time_yrs)
  )) %>% 
  ungroup() %>% 
  left_join(., enframe(sites_full), by = c("site" = "name")) %>% 
  rename(site_full = value) %>% 
  mutate(site_full = fct_relevel(site_full, "Arroyo Quemado (AQUE)", "Naples (NAPL)", "Isla Vista (IVEE)", "Mohawk (MOHK)", "Carpinteria (CARP)")) %>% 
  # create a new column for "kelp year"
  mutate(quarter = fct_relevel(quarter, "Q2", "Q3", "Q4", "Q1")) %>% 
  mutate(kelp_year = case_when(
    quarter %in% c("Q2", "Q3", "Q4") ~ year,
    quarter == "Q1" ~ year - 1
  )) %>% 
  mutate(kelp_year = paste("kelp_", kelp_year, "-", kelp_year + 1, sep = "")) %>% 
  # create a column for the points to compare for "2 year interval"
  mutate(comp_2yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2008-2009", "kelp_2009-2010") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_2yrs = fct_relevel(comp_2yrs, "start", "during", "after")) %>% 
  # create a column for the points to compare for "3 year interval"
  mutate(comp_3yrs = case_when(
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2008-2009", "kelp_2009-2010", "kelp_2010-2011") ~ "start",
    site %in% c("aque", "napl", "mohk", "carp") & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during", 
    site == "ivee" & kelp_year %in% c("kelp_2011-2012", "kelp_2012-2013", "kelp_2013-2014") ~ "start",
    site == "ivee" & kelp_year %in% c("kelp_2014-2015", "kelp_2015-2016", "kelp_2016-2017") ~ "during",
    kelp_year %in% c("kelp_2019-2020", "kelp_2020-2021", "kelp_2021-2022") ~ "after"
  )) %>% 
  mutate(comp_3yrs = fct_relevel(comp_3yrs, "start", "during", "after"))
```

```{r}
algae_spp_annual_means <- delta_algae_spp_annual %>% 
  group_by(site, sp_code, kelp_year) %>% 
  mutate(mean_delta = mean(delta_annual), 
         mean_tse = mean(time_since_end),
         se_delta = se(delta_annual)) %>% 
  dplyr::select(site, site_full, kelp_year, sp_code, mean_delta, mean_tse, exp_dates, se_delta) %>% 
  unique() %>% 
  full_join(., site_quality, by = "site")

algae_spp_annual_after_means <- algae_spp_annual_means %>% 
  filter(exp_dates == "after")

linear_model_sel_during <- lm(mean_delta ~ mean_tse + quality + sp_code + mean_tse*quality + mean_tse*sp_code + sp_code*quality, data = (algae_spp_annual_means %>% filter(exp_dates == "during")), na.action = na.pass)
summary(linear_model_sel_during)
plot(simulateResiduals(linear_model_sel_during))
# ggeffects
predicted_during <- ggpredict(linear_model_sel_during, terms = ~ mean_tse + quality + sp_code + mean_tse*quality + mean_tse*sp_code + sp_code*quality, type = "fixed") %>% 
  rename("quality" = group) %>% 
  rename("sp_code" = facet)

linear_model <- lm(mean_delta ~ mean_tse + quality + sp_code + mean_tse*quality + mean_tse*sp_code + sp_code*quality, data = algae_spp_annual_after_means, na.action = na.pass)
dredge(linear_model) %>% 
  model.sel() %>% 
  gt()
linear_model_sel <- glm(mean_delta ~ mean_tse + quality + sp_code + mean_tse*quality + mean_tse*sp_code + sp_code*quality, data = algae_spp_annual_after_means, na.action = na.pass)
summary(linear_model_sel)
plot(simulateResiduals(linear_model_sel))
# ggeffects
predicted <- ggpredict(linear_model_sel, terms = ~ mean_tse + quality + sp_code + mean_tse*quality + mean_tse*sp_code + sp_code*quality, type = "fixed") %>% 
  rename("quality" = group) %>% 
  rename("sp_code" = facet)
# emmeans
grid <- ref_grid(linear_model_sel, cov.keep = c("mean_tse", "quality", "sp_code"))
emm <- emmeans(grid, spec = c("mean_tse", "quality", "sp_code"), level = 0.95) %>% 
  data.frame(.)

annual_algae_spp_sitequality_ggpredict <- ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  # raw data: means and error bars
  facet_wrap(~sp_code+quality, ncol = 3) +
  geom_point(data = algae_spp_annual_means, aes(x = mean_tse, y = mean_delta, shape = exp_dates, col = sp_code), alpha = 0.6) +
  scale_shape_manual(values = c("during" = 1, "after" = 16), guide = "none") +
  # predicted values: during
  geom_ribbon(data = predicted_during, aes(x = x, y = predicted, ymin = conf.low, ymax = conf.high, fill = sp_code), alpha = 0.2) +
  geom_line(data = predicted_during, aes(x = x, y = predicted, group = sp_code, col = sp_code), size = 1) +
  # predicted values: after
  geom_ribbon(data = predicted, aes(x = x, y = predicted, ymin = conf.low, ymax = conf.high, fill = sp_code), alpha = 0.2, show.legend = TRUE) +
  geom_line(data = predicted, aes(x = x, y = predicted, group = sp_code, col = sp_code), size = 1) +
  # theme
  theme_bw() + 
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size = 18),
        axis.text = element_text(size = 10),
        strip.text = element_text(size = 10),
        legend.position = "none") +
  labs(x = "Time since end of experiment", y = "\U0394 biomass (treatment - control)",
       title = "Focal algal species",
       caption = "ggpredict")

ggsave(here::here("figures", "algae_biomass_ts-grid.jpg"), annual_algae_spp_sitequality_ggpredict, 
       height = 16, width = 8, dpi = 300)

annual_algae_sitequality_emmeans <- ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  facet_wrap(~quality, nrow = 1) +
  geom_point(data = algae_spp_annual_means, aes(x = mean_tse, y = mean_delta, color = exp_dates, shape = site)) +
  scale_color_manual(values = c("during" = "grey", "after" = "black"), guide = "none") +
  # predicted values
  geom_ribbon(data = emm, aes(x = mean_tse, y = emmean, ymin = lower.CL, ymax = upper.CL, fill = sp_code), alpha = 0.2, show.legend = FALSE) +
  geom_line(data = emm, aes(x = mean_tse, y = emmean, group = sp_code)) +
  theme_bw() + 
  theme(axis.title = element_text(size = 14),
        plot.title = element_text(size = 18),
        axis.text = element_text(size = 10),
        strip.text = element_text(size = 10)) +
  labs(x = "Time since end of experiment", y = "\U0394 biomass (treatment - control)",
       title = "Focal algal species", 
       caption = "emmeans")
```

