---
title: "Functional group recovery"
author: "An Bui"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("code", "00-set_up.R"))
```

# Set up data frame

```{r}
fg_recovery_annual <- biomass %>% 
  # make a new column for after dates
  after_dates_column() %>% 
  # make a new column for during and after and set factor levels
  exp_dates_column() %>% 
  new_group_column() %>% 
  dplyr::select(site, year, month, treatment, date, exp_dates, dry_gm2) %>% 
  group_by(site, exp_dates, year, month, treatment, date) %>% 
  summarize(total_dry = sum(dry_gm2)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = treatment, values_from = total_dry) %>% 
  mutate(delta_annual = annual - control,
         delta_continual = continual - control) 
  # create a column for quarter
  mutate(quarter = case_when(
    month <= 3 ~ "Q1",
    month <= 6 ~ "Q2",
    month <= 9 ~ "Q3",
    TRUE ~ "Q4"
  )) %>% 
  # calculate time since start of experiment
  mutate(time_yrs = case_when(
    # AQUE, NAPL, MOHK, CARP: control and annual started in 2008
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q1" & treatment %in% c("annual", "control") ~ year + 0.125 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q2" & treatment %in% c("annual", "control") ~ year + 0.375 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q3" & treatment %in% c("annual", "control") ~ year + 0.625 - 2008,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q4" & treatment %in% c("annual", "control") ~ year + 0.875 - 2008, 
    # IVEE control and annual started in 2011
    site == "ivee" & quarter == "Q1" & treatment %in% c("annual", "control") ~ year + 0.125 - 2011,
    site == "ivee" & quarter == "Q2" & treatment %in% c("annual", "control") ~ year + 0.375 - 2011,
    site == "ivee" & quarter == "Q3" & treatment %in% c("annual", "control") ~ year + 0.625 - 2011,
    site == "ivee" & quarter == "Q4" & treatment %in% c("annual", "control") ~ year + 0.875 - 2011,
    # AQUE, NAPL, MOHK, CARP: continual started in 2010
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q1" & treatment == "continual" ~ year + 0.125 - 2010,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q2" & treatment == "continual" ~ year + 0.375 - 2010,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q3" & treatment == "continual" ~ year + 0.625 - 2010,
    site %in% c("aque", "napl", "mohk", "carp") & quarter == "Q4" & treatment == "continual" ~ year + 0.875 - 2010
  )) %>% 
  group_by(site) %>% 
  mutate(time_since_start = time_yrs - min(time_yrs)) %>% 
  ungroup() %>% 
  # calculate time since end of experiment
  mutate(time_yrs_end = case_when(
    # annual
    # AQUE
    site == "aque" & quarter == "Q1" & treatment == "annual" ~ year + 0.125 - 2018,
    site == "aque" & quarter == "Q2" & treatment == "annual" ~ year + 0.375 - 2018,
    site == "aque" & quarter == "Q3" & treatment == "annual" ~ year + 0.625 - 2018,
    site == "aque" & quarter == "Q4" & treatment == "annual" ~ year + 0.875 - 2018,
    # NAPL
    site == "napl" & quarter == "Q1" & treatment == "annual" ~ year + 0.125 - 2017,
    site == "napl" & quarter == "Q2" & treatment == "annual" ~ year + 0.375 - 2017,
    site == "napl" & quarter == "Q3" & treatment == "annual" ~ year + 0.625 - 2017,
    site == "napl" & quarter == "Q4" & treatment == "annual" ~ year + 0.875 - 2017,
    # IVEE
    site == "ivee" & quarter == "Q1" & treatment == "annual" ~ year + 0.125 - 2017,
    site == "ivee" & quarter == "Q2" & treatment == "annual" ~ year + 0.375 - 2017,
    site == "ivee" & quarter == "Q3" & treatment == "annual" ~ year + 0.625 - 2017,
    site == "ivee" & quarter == "Q4" & treatment == "annual" ~ year + 0.875 - 2017,
    # MOHK 
    site == "mohk" & quarter == "Q1" & treatment == "annual" ~ year + 0.125 - 2018,
    site == "mohk" & quarter == "Q2" & treatment == "annual" ~ year + 0.375 - 2018,
    site == "mohk" & quarter == "Q3" & treatment == "annual" ~ year + 0.625 - 2018,
    site == "mohk" & quarter == "Q4" & treatment == "annual" ~ year + 0.875 - 2018,
    # CARP
    site == "carp" & quarter == "Q1" & treatment == "annual" ~ year + 0.125 - 2018,
    site == "carp" & quarter == "Q2" & treatment == "annual" ~ year + 0.375 - 2018,
    site == "carp" & quarter == "Q3" & treatment == "annual" ~ year + 0.625 - 2018,
    site == "carp" & quarter == "Q4" & treatment == "annual" ~ year + 0.875 - 2018,
    # continual
    # AQUE
    site == "aque" & quarter == "Q1" & treatment == "continual" ~ year + 0.125 - 2017,
    site == "aque" & quarter == "Q2" & treatment == "continual" ~ year + 0.375 - 2017,
    site == "aque" & quarter == "Q3" & treatment == "continual" ~ year + 0.625 - 2017,
    site == "aque" & quarter == "Q4" & treatment == "continual" ~ year + 0.875 - 2017,
    # NAPL
    site == "napl" & quarter == "Q1" & treatment == "continual" ~ year + 0.125 - 2016,
    site == "napl" & quarter == "Q2" & treatment == "continual" ~ year + 0.375 - 2016,
    site == "napl" & quarter == "Q3" & treatment == "continual" ~ year + 0.625 - 2016,
    site == "napl" & quarter == "Q4" & treatment == "continual" ~ year + 0.875 - 2016,
    # MOHK 
    site == "mohk" & quarter == "Q1" & treatment == "continual" ~ year + 0.125 - 2017,
    site == "mohk" & quarter == "Q2" & treatment == "continual" ~ year + 0.375 - 2017,
    site == "mohk" & quarter == "Q3" & treatment == "continual" ~ year + 0.625 - 2017,
    site == "mohk" & quarter == "Q4" & treatment == "continual" ~ year + 0.875 - 2017,
    # CARP
    site == "carp" & quarter == "Q1" & treatment == "continual" ~ year + 0.125 - 2017,
    site == "carp" & quarter == "Q2" & treatment == "continual" ~ year + 0.375 - 2017,
    site == "carp" & quarter == "Q3" & treatment == "continual" ~ year + 0.625 - 2017,
    site == "carp" & quarter == "Q4" & treatment == "continual" ~ year + 0.875 - 2017,
    # control
    # AQUE
    site == "aque" & quarter == "Q1" & treatment == "control" ~ year + 0.125 - 2017,
    site == "aque" & quarter == "Q2" & treatment == "control" ~ year + 0.375 - 2017,
    site == "aque" & quarter == "Q3" & treatment == "control" ~ year + 0.625 - 2017,
    site == "aque" & quarter == "Q4" & treatment == "control" ~ year + 0.875 - 2017,
    # NAPL
    site == "napl" & quarter == "Q1" & treatment == "control" ~ year + 0.125 - 2016,
    site == "napl" & quarter == "Q2" & treatment == "control" ~ year + 0.375 - 2016,
    site == "napl" & quarter == "Q3" & treatment == "control" ~ year + 0.625 - 2016,
    site == "napl" & quarter == "Q4" & treatment == "control" ~ year + 0.875 - 2016,
    # IVEE
    site == "ivee" & quarter == "Q1" & treatment == "control" ~ year + 0.125 - 2017,
    site == "ivee" & quarter == "Q2" & treatment == "control" ~ year + 0.375 - 2017,
    site == "ivee" & quarter == "Q3" & treatment == "control" ~ year + 0.625 - 2017,
    site == "ivee" & quarter == "Q4" & treatment == "control" ~ year + 0.875 - 2017,
    # MOHK 
    site == "mohk" & quarter == "Q1" & treatment == "control" ~ year + 0.125 - 2017,
    site == "mohk" & quarter == "Q2" & treatment == "control" ~ year + 0.375 - 2017,
    site == "mohk" & quarter == "Q3" & treatment == "control" ~ year + 0.625 - 2017,
    site == "mohk" & quarter == "Q4" & treatment == "control" ~ year + 0.875 - 2017,
    # CARP
    site == "carp" & quarter == "Q1" & treatment == "control" ~ year + 0.125 - 2017,
    site == "carp" & quarter == "Q2" & treatment == "control" ~ year + 0.375 - 2017,
    site == "carp" & quarter == "Q3" & treatment == "control" ~ year + 0.625 - 2017,
    site == "carp" & quarter == "Q4" & treatment == "control" ~ year + 0.875 - 2017,
  )) %>% 
  group_by(site, exp_dates) %>% 
  mutate(time_since_end = case_when(
    exp_dates == "during" ~ time_yrs_end,
    exp_dates == "after" ~ time_yrs_end - min(time_yrs_end)
  )) %>% 
  ungroup() %>% 
  mutate(treatment = fct_relevel(treatment, "control", "annual", "continual"))
```

# Some plots

```{r}
ggplot(fg_recovery %>% filter(sp_code == "MAPY"), aes(x = treatment, y = dry_gm2)) +
  stat_summary(aes(group = treatment), fun.data = "mean_cl_boot", geom = "errorbar", width = 0.5, size = 1, na.rm = TRUE) +
  stat_summary(aes(col = treatment), fun = "mean", geom = "point", size = 10, na.rm = TRUE) +
  scale_color_manual(values = color_palette) +
  labs(x = "Treatment", y = expression(paste("Biomass (g dry/", "m"^2, ")", sep = "")),
       title = "Giant kelp biomass") +
  theme_bw() +
  theme(axis.text = element_text(size = 16),
        axis.title = element_text(size = 16),
        axis.ticks = element_line(size = 1),
        axis.ticks.length = unit(0.4, "cm"),
        strip.text = element_text(size = 14), 
        plot.title = element_text(size = 20), 
        legend.position = "none") +
  facet_wrap(~exp_dates)
  # ggsave(here::here("figures/fg-recovery", paste("biomass_MAPY_", todays_date, ".jpg", sep = "")))

ggplot(fg_recovery %>% filter(sp_code != "MAPY" & group == "algae"), aes(x = treatment, y = dry_gm2)) +
  stat_summary(aes(group = treatment), fun.data = "mean_cl_boot", geom = "errorbar", width = 0.5, size = 1, na.rm = TRUE) +
  stat_summary(aes(col = treatment), fun = "mean", geom = "point", size = 10, na.rm = TRUE) +
  scale_color_manual(values = color_palette) +
  labs(x = "Treatment", y = expression(paste("Biomass (g dry/", "m"^2, ")", sep = "")),
       title = "Understory macroalgal biomass") +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        axis.ticks = element_line(size = 1),
        axis.ticks.length = unit(0.4, "cm"),
        strip.text = element_text(size = 24),
        plot.title = element_text(size = 26),
        legend.position = "none") +
  facet_wrap(~exp_dates) +
  ggsave(here::here("figures/fg-recovery", paste("biomass_understory-algae_", todays_date, ".jpg", sep = "")))

ggplot(fg_recovery %>% filter(group == "fish"), aes(x = treatment, y = dry_gm2)) +
  stat_summary(aes(group = treatment), fun.data = "mean_cl_boot", geom = "errorbar", width = 0.5, size = 1, na.rm = TRUE) +
  stat_summary(aes(col = treatment), fun = "mean", geom = "point", size = 10, na.rm = TRUE) +
  scale_color_manual(values = color_palette) +
  labs(x = "Treatment", y = expression(paste("Biomass (g dry/", "m"^2, ")", sep = "")),
       title = "Fish biomass", caption = "outliers not removed") +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        axis.ticks = element_line(size = 1),
        axis.ticks.length = unit(0.4, "cm"),
        strip.text = element_text(size = 24), 
        plot.title = element_text(size = 26), 
        legend.position = "none") +
  facet_wrap(~exp_dates) +
  ggsave(here::here("figures/fg-recovery", paste("biomass_fish_", todays_date, ".jpg", sep = "")))

ggplot(fg_recovery %>% filter(mobility == "sessile" & group == "invert"), aes(x = treatment, y = dry_gm2)) +
  stat_summary(aes(group = treatment), fun.data = "mean_cl_boot", geom = "errorbar", width = 0.5, size = 1, na.rm = TRUE) +
  stat_summary(aes(col = treatment), fun = "mean", geom = "point", size = 10, na.rm = TRUE) +
  scale_color_manual(values = color_palette) +
  labs(x = "Treatment", y = expression(paste("Biomass (g dry/", "m"^2, ")", sep = "")),
       title = "Sessile invert biomass") +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        axis.ticks = element_line(size = 1),
        axis.ticks.length = unit(0.4, "cm"),
        strip.text = element_text(size = 24), 
        plot.title = element_text(size = 26), 
        legend.position = "none") +
  facet_wrap(~exp_dates) +
  ggsave(here::here("figures/fg-recovery", paste("biomass_sessile-inverts_", todays_date, ".jpg", sep = "")))

ggplot(fg_recovery %>% filter(mobility == "mobile" & group == "invert"), aes(x = treatment, y = dry_gm2)) +
  stat_summary(aes(group = treatment), fun.data = "mean_cl_boot", geom = "errorbar", width = 0.5, size = 1, na.rm = TRUE) +
  stat_summary(aes(col = treatment), fun = "mean", geom = "point", size = 10, na.rm = TRUE) +
  scale_color_manual(values = color_palette) +
  labs(x = "Treatment", y = expression(paste("Biomass (g dry/", "m"^2, ")", sep = "")),
       title = "Mobile invert biomass") +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        axis.ticks = element_line(size = 1),
        axis.ticks.length = unit(0.4, "cm"),
        strip.text = element_text(size = 24), 
        plot.title = element_text(size = 26), 
        legend.position = "none") +
  facet_wrap(~exp_dates) +
  ggsave(here::here("figures/fg-recovery", paste("biomass_mobile-inverts_", todays_date, ".jpg", sep = "")))

```

# Log response ratio

```{r}
df2 <- fg_recovery %>% 
  filter(sp_code != "MAPY") %>% 
  select(site, year, month, treatment, date, exp_dates, group, mobility, dry_gm2) %>% 
  group_by(exp_dates, group, mobility, treatment) %>% 
  summarize(mean_biomass = mean(dry_gm2, na.rm = TRUE)) %>% 
  pivot_wider(names_from = treatment, values_from = mean_biomass) %>% 
  mutate(lrr_annual = log2(mean(annual)/mean(control)),
         lrr_continual = log2(mean(continual, na.rm = TRUE)/mean(control, na.rm = TRUE)),
         group_mobility = paste(group, mobility, sep = "_"))

ggplot(df2) +
  geom_hline(yintercept = 0, lty = 2, col = "grey") +
  geom_point(aes(x = group_mobility, y = lrr_annual), size = 5) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title = element_text(size = 20),
        axis.ticks = element_line(size = 1),
        axis.ticks.length = unit(0.4, "cm"),
        strip.text = element_text(size = 24), 
        plot.title = element_text(size = 26), 
        legend.position = "none") +
  labs(x = "Groups", y = "Log response ratio",
       title = "Annual log response ratio") +
  facet_wrap(~exp_dates) 
  # ggsave(here::here("figures/fg-recovery", paste("annual-log-response-ratio_", todays_date, ".jpg", sep = "")))

ggplot(df2) +
  geom_hline(yintercept = 0, lty = 2, col = "grey") +
  geom_point(aes(x = group_mobility, y = lrr_continual), size = 5) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title = element_text(size = 20),
        axis.ticks = element_line(size = 1),
        axis.ticks.length = unit(0.4, "cm"),
        strip.text = element_text(size = 24), 
        plot.title = element_text(size = 26), 
        legend.position = "none") +
  labs(x = "Groups", y = "Log response ratio",
       title = "Continual log response ratio") +
  facet_wrap(~exp_dates) 
  # ggsave(here::here("figures/fg-recovery", paste("continual-log-response-ratio_", todays_date, ".jpg", sep = "")))
  
```

```{r}
spp_recovery <- fg_recovery %>% 
  filter(sp_code != "MAPY") %>% 
  filter(year < 2017) %>% 
  dplyr::select(site, treatment, exp_dates, sp_code, dry_gm2) %>%
  group_by(treatment, exp_dates, sp_code) %>% 
  summarize(mean_biomass = mean(dry_gm2, na.rm = TRUE),
            sample_n = length(dry_gm2),
            se_biomass = sd(dry_gm2, na.rm = TRUE)/sqrt(sample_n)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = treatment, values_from = c(mean_biomass, se_biomass, sample_n)) %>% 
  rowwise() %>% 
  # log response ratio, degrees of freedom, tscore, margin error with 95% confidence interval
  mutate(# log response ratio
         lrr_annual = log2(mean_biomass_annual/mean_biomass_control),
         lrr_continual = log2(mean_biomass_continual/mean_biomass_control),
         # degrees of freedom
         df_annual = sample_n_annual - 1,
         df_continual = sample_n_continual - 1,
         # tscore
         tscore_annual = qt(p = 0.5/2, df = df_annual, lower.tail = FALSE),
         tscore_continual = qt(p = 0.5/2, df = df_continual, lower.tail = FALSE),
         # margin error
         me_annual = tscore_annual*se_biomass_annual,
         me_continual = tscore_continual*se_biomass_continual
         ) %>% 
  ungroup() %>% 
  # attach the spp_names df to get scientific name, taxon info, etc.
  left_join(., spp_names, by = "sp_code")

LRRd(spp_recovery$mean_biomass_continual, spp_recovery$mean_biomass_control)

algae_2018 <- c("EGME", "TALE", "CYOS", "PTCA", "SAMU", "CC", "R", "DL", "CO", "GS", "RAT", "EC", "POLA")


lrr_understory_annual <- spp_recovery %>% 
  filter(sp_code %in% algae_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "EGME", "TALE", "CYOS", "PTCA", "SAMU", "CC", "R", "DL", "CO", "GS", "RAT", "EC", "POLA")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_annual), size = 5) +
  geom_linerange(aes(x = sp_code, y = lrr_annual, ymin = lrr_annual - me_annual, ymax = lrr_annual + me_annual), size = 1) +
  labs(x = "Species", y = "Log response ratio",
       title = "Understory algae: annual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20)) +
  facet_wrap(~exp_dates) 
# ggsave(here::here("figures/fg-recovery", paste("lrr_understory_annual_", todays_date, ".jpg", sep = "")), lrr_understory_annual, width = 8, height = 6)

lrr_understory_continual <- spp_recovery %>% 
  filter(sp_code %in% algae_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "EGME", "TALE", "CYOS", "PTCA", "SAMU", "CC", "R", "DL", "CO", "GS", "RAT", "EC", "POLA")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_continual), size = 5) +
  geom_linerange(aes(x = sp_code, y = lrr_continual, ymin = lrr_continual - me_continual, ymax = lrr_continual + me_continual), size = 1) +
  labs(x = "Species", y = "Log response ratio",
       title = "Understory algae: continual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20), 
        panel.grid = element_blank()) +
  facet_wrap(~exp_dates) 
# ggsave(here::here("figures/fg-recovery", paste("lrr_understory_continual_", todays_date, ".jpg", sep = "")), lrr_understory_continual, width = 8, height = 6)

herbs_2018 <- c("OPSP", "SPL", "LIGL", "SFL", "MECR")

lrr_herbs_annual <- spp_recovery %>% 
  filter(sp_code %in% herbs_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "OPSP", "SPL", "LIGL", "SFL", "MECR")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_annual), size = 5) +
  geom_linerange(aes(x = sp_code, y = lrr_annual, ymin = lrr_annual - me_annual, ymax = lrr_annual + me_annual), size = 1) +
  labs(x = "Species", y = "Log response ratio",
       title = "Mobile invertebrates: annual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20)) +
  facet_wrap(~exp_dates) 
# ggsave(here::here("figures/fg-recovery", paste("lrr_herbs_annual", todays_date, ".jpg", sep = "")), lrr_herbs_annual, width = 8, height = 6)

lrr_herbs_continual <- spp_recovery %>% 
  filter(sp_code %in% herbs_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "OPSP", "SPL", "LIGL", "SFL", "MECR")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_continual), size = 5) +
  geom_linerange(aes(x = sp_code, y = lrr_continual, ymin = lrr_continual - me_continual, ymax = lrr_continual + me_continual), size = 1) +
  labs(x = "Species", y = "Log response ratio",
       title = "Mobile invertebrates: continual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20)) +
  facet_wrap(~exp_dates) 
# ggsave(here::here("figures/fg-recovery", paste("lrr_herbs_continual", todays_date, ".jpg", sep = "")), lrr_herbs_continual, width = 8, height = 6)

fishes_2018 <- c("SMAR", "OELO", "BFRE", "OPIC", "OCAL", "SPUL", "HCAR", 
                 "PCAL", "GNIG", "CPUN", "TSEM", "RTOX", "SATR", "EJAC",
                 "MCAL", "CSAT", "ANDA")

lrr_fishes_annual <- spp_recovery %>% 
  filter(sp_code %in% fishes_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "SMAR", "OELO", "BFRE", "OPIC", "OCAL", "SPUL", "HCAR", 
                 "PCAL", "GNIG", "CPUN", "TSEM", "RTOX", "SATR", "EJAC",
                 "MCAL", "CSAT", "ANDA")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_annual), size = 5) +
  geom_linerange(aes(x = sp_code, y = lrr_annual, ymin = lrr_annual - me_annual, ymax = lrr_annual + me_annual), size = 1) +
  labs(x = "Species", y = "Log response ratio",
       title = "Fish: annual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20)) +
  facet_wrap(~exp_dates) 
# ggsave(here::here("figures/fg-recovery", paste("lrr_fishes_annual", todays_date, ".jpg", sep = "")), lrr_fishes_annual, width = 8, height = 6)

lrr_fishes_continual <- spp_recovery %>% 
  filter(sp_code %in% fishes_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "SMAR", "OELO", "BFRE", "OPIC", "OCAL", "SPUL", "HCAR", 
                 "PCAL", "GNIG", "CPUN", "TSEM", "RTOX", "SATR", "EJAC",
                 "MCAL", "CSAT", "ANDA")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_continual), size = 5) +
  geom_linerange(aes(x = sp_code, y = lrr_continual, ymin = lrr_continual - me_continual, ymax = lrr_continual + me_continual), size = 1) +
  labs(x = "Species", y = "Log response ratio",
       title = "Fish: continual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20)) +
  facet_wrap(~exp_dates) 
# ggsave(here::here("figures/fg-recovery", paste("lrr_fishes_continual", todays_date, ".jpg", sep = "")), lrr_fishes_continual, width = 8, height = 6)

epi_inv_2018 <- c("TEAU", "URLO", "MUCA", "DIOR", "ANSP", "CUPI", "CUSP", "STMO")

lrr_epi_inv_annual <- spp_recovery %>% 
  filter(sp_code %in% epi_inv_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "TEAU", "URLO", "MUCA", "DIOR", "ANSP", "CUPI", "CUSP", "STMO")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_annual), size = 5) +
  geom_linerange(aes(x = sp_code, y = lrr_annual, ymin = lrr_annual - me_annual, ymax = lrr_annual + me_annual), size = 1) +
  labs(x = "Species", y = "Log response ratio",
       title = "Epilithic sessile inverts: annual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20)) +
  facet_wrap(~exp_dates) 
# ggsave(here::here("figures/fg-recovery", paste("lrr_epi_inv_annual", todays_date, ".jpg", sep = "")), lrr_epi_inv_annual, width = 8, height = 6)

lrr_epi_inv_continual <- spp_recovery %>% 
  filter(sp_code %in% epi_inv_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "TEAU", "URLO", "MUCA", "DIOR", "ANSP", "CUPI", "CUSP", "STMO")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_continual), size = 5) +
  geom_linerange(aes(x = sp_code, y = lrr_continual, ymin = lrr_continual - me_continual, ymax = lrr_continual + me_continual), size = 1) +
  scale_y_continuous(limits = c(-12, 12)) +
  labs(x = "Species", y = "Log response ratio",
       title = "Epilithic sessile inverts: continual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20),
        panel.grid = element_blank()) +
  facet_wrap(~exp_dates) 
# ggsave(here::here("figures/fg-recovery", paste("lrr_epi_inv_continual", todays_date, ".jpg", sep = "")), lrr_epi_inv_continual, width = 8, height = 6)

end_inv_2018 <- c("CHOV", "PACA")

lrr_end_inv_annual <- spp_recovery %>% 
  filter(sp_code %in% end_inv_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "CHOV", "PACA")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_annual), size = 5) +
  # geom_linerange(aes(x = sp_code, y = lrr_annual, ymin = lrr_annual - me_annual, ymax = lrr_annual + me_annual), size = 1) +
  labs(x = "Species", y = "Log response ratio",
       title = "Endolithic sessile inverts: annual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20)) +
  facet_wrap(~exp_dates, scales = "free") 
# ggsave(here::here("figures/fg-recovery", paste("lrr_end_inv_annual", todays_date, ".jpg", sep = "")), lrr_end_inv_annual, width = 8, height = 6)

lrr_end_inv_continual <- spp_recovery %>% 
  filter(sp_code %in% end_inv_2018) %>% 
  mutate(sp_code = fct_relevel(sp_code, "CHOV", "PACA")) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2, color = "grey") +
  geom_point(aes(x = sp_code, y = lrr_continual), size = 5) +
  geom_linerange(aes(x = sp_code, y = lrr_continual, ymin = lrr_continual - me_continual, ymax = lrr_continual + me_continual), size = 1) +
  labs(x = "Species", y = "Log response ratio",
       title = "Endolithic sessile inverts: continual") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(size = 16),
        axis.title = element_text(size = 20),
        strip.text = element_text(size = 16),
        plot.title = element_text(size = 20)) +
  facet_wrap(~exp_dates) 
# ggsave(here::here("figures/fg-recovery", paste("lrr_end_inv_continual", todays_date, ".jpg", sep = "")), lrr_end_inv_continual, width = 8, height = 6)

```

# timeseries

Species from rank abundance curves: `algae_selection`

```{r}
algae_prop <- biomass %>%
  dplyr::select(sample_ID, site, year, date, treatment, sp_code, dry_gm2) %>%
  # create a new column where total biomass is calculated
  group_by(sample_ID) %>%
  mutate(total_dry = sum(dry_gm2)) %>%
  ungroup() %>%
  # create a new column where total biomass for the species for the whole survey is calculated
  group_by(sample_ID, sp_code) %>%
  mutate(total_sp_dry = sum(dry_gm2)) %>%
  ungroup() %>%
  # create a new column where percent of total biomass per survey for each species is calculated
  mutate(percent_sp_dry = total_sp_dry/total_dry) %>%
  # double check to make sure the percents worked out...
  dplyr::select(sample_ID, site, year, date, sp_code,
         # values that need to be unique:
         total_sp_dry, percent_sp_dry) %>%
  unique() %>%
  group_by(sample_ID) %>%
  mutate(total_percent = sum(percent_sp_dry)) 

algae_prop %>% 
  filter(sp_code %in% algae_selection) %>% 
  ggplot(aes(x = date, y = percent_sp_dry)) +
  stat_summary(aes(col = sp_code), fun = "sum", geom = "line", size = 1) +
  stat_summary(aes(col = sp_code), fun = "sum", geom = "point", size = 2) +
  facet_wrap(~site)
```



