---
title: "exam figures"
author: "An Bui"
date: "5/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source(here::here("code", "00-set_up.R"))

library(patchwork)
```

# 1. Kelp biomass

## Cleaning
```{r}
kelp_fronds <- read_csv(here::here("data", "LTE_Kelp_All_Years_20210209.csv")) %>% 
  clean_names() %>% 
  # create a sample_ID for each sampling date at each treatment at each site
  unite("sample_ID", site, treatment, date, remove = FALSE) %>% 
  # change to lower case
  mutate_at(c("group", "mobility", "growth_morph"), str_to_lower) %>% 
  # make a new column designating "start", "during" and "after" removal
  mutate(exp_dates = case_when(
    site == "NAPL" & sample_ID %in% napl_start_dates ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & sample_ID %in% mohk_start_dates ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & sample_ID %in% aque_start_dates ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & sample_ID %in% carp_start_dates ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & sample_ID %in% ivee_start_dates ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  select(1:14) %>% 
  filter(fronds > -1) %>% 
  mutate(season = case_when(
    month %in% c(12, 1, 2) ~ "winter",
    month %in% c(3, 4, 5) ~ "spring",
    month %in% c (6, 7, 8) ~ "summer",
    month %in% c(9, 10, 11) ~ "fall"
    ),
    season = fct_relevel(season, "winter", "spring", "summer", "fall"))

# get difference in fronds between control and removal plots
delta_fronds <- kelp_fronds %>% 
  group_by(site, year, month, season, treatment, date) %>% 
  summarize(total_fronds = sum(fronds)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  filter(total_fronds > -1) %>% 
  pivot_wider(names_from = treatment, values_from = total_fronds) %>% 
  mutate(delta_annual = CONTROL - ANNUAL,
         delta_continual = CONTROL - CONTINUAL) 

# just control
control_fronds <- kelp_fronds %>% 
  filter(treatment == "CONTROL") %>% 
  group_by(site, year, month, season, date) %>% 
  summarize(total_fronds = sum(fronds)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  filter(total_fronds > -1)

# total fronds
total_fronds <- kelp_fronds %>% 
  group_by(site, year, month, treatment, season, date) %>% 
  summarize(total_fronds = sum(fronds)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  filter(total_fronds > -1) 
  
```

## Testing plots
```{r}
ggplot() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  geom_point(data = delta_fronds %>% filter(site == "CARP" & delta_annual != "NA"), 
             aes(x = date, y = delta_annual, color = "Annual")) +
  geom_line(data = delta_fronds %>% filter(site == "CARP" & delta_annual != "NA"),
            aes(x = date, y = delta_annual, color = "Annual")) +
  geom_point(data = delta_fronds %>% filter(site == "CARP" & delta_continual != "NA"), 
             aes(x = date, y = delta_continual, color = "Continual")) +
  geom_line(data = delta_fronds %>% filter(site == "CARP" & delta_continual != "NA"),
            aes(x = date, y = delta_continual, color = "Continual")) +
  geom_vline(xintercept = aque_after_date, aes(color = "End"), show.legend = NA) +
  scale_color_manual(name = NULL,
                     breaks = c("Annual", "Continual", "End"),
                     values = c("Annual" = "green", "Continual" = "blue", "End" = "red")) +
  theme_bw() + 
  labs(title = "CARP kelp biomass", 
       x = "Sampling date",
       y = expression(Delta~"kelp fronds"~"(removal - control)"))

ggplot(data = total_fronds %>% filter(site == "AQUE"),
             aes(x = date, y = total_fronds, color = treatment, shape = treatment)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  geom_point(size = 2) +
  geom_line() +
  geom_vline(xintercept = aque_after_date, aes(color = "#FFFFFF"), show.legend = NA) +
  scale_color_manual(name = NULL,
                     breaks = c("ANNUAL", "CONTINUAL", "CONTROL"),
                     values = c("ANNUAL" = annual_col, "CONTINUAL" = continual_col, "CONTROL" = "grey")) +
    scale_shape_manual(name = NULL,
                     breaks = c("ANNUAL", "CONTINUAL", "CONTROL"),
                     values = c("ANNUAL" = annual_shape, "CONTINUAL" = continual_shape, "CONTROL" = 21)) +
  theme_bw() + 
  labs(title = "AQUE kelp biomass", 
       x = "Sampling date",
       y = "Frond density")
```

## Plotting timeseries

This is delta biomass
```{r}
total_frond_timeseries_fxn <- function(site_choice) {
  after_date <- if(site_choice == "AQUE") {
    aque_after_date
  } else if(site_choice == "NAPL") {
    napl_after_date
  } else if(site_choice == "CARP") {
    carp_after_date
  } else if(site_choice == "IVEE") {
    ivee_after_date
  } else if(site_choice == "MOHK") {
    mohk_after_date
  }
  
  ggplot(data = total_fronds %>% filter(site == site_choice),
         aes(x = date, y = total_fronds, color = treatment, shape = treatment)) +
    scale_x_date(limits = c(aque_start_date, as.Date("2021-10-02"))) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
    geom_point(size = 2) +
    geom_line() +
    geom_vline(xintercept = after_date, show.legend = NA) +
    scale_color_manual(name = NULL,
                       breaks = c("ANNUAL", "CONTINUAL", "CONTROL"),
                       values = c("ANNUAL" = annual_col, "CONTINUAL" = continual_col, "CONTROL" = "grey")) +
    scale_shape_manual(name = NULL,
                       breaks = c("ANNUAL", "CONTINUAL", "CONTROL"),
                       values = c("ANNUAL" = annual_shape, "CONTINUAL" = continual_shape, "CONTROL" = 21))  +
    theme_bw() + 
    labs(title = site_choice,
         x = " ",
         y = " ")
}

aque_total_frond_timeseries <- total_frond_timeseries_fxn("AQUE")
mohk_total_frond_timeseries <- total_frond_timeseries_fxn("MOHK")
carp_total_frond_timeseries <- total_frond_timeseries_fxn("CARP")
ivee_total_frond_timeseries <- ggplot(data = total_fronds %>% filter(site == "IVEE"),
         aes(x = date, y = total_fronds, color = treatment, shape = treatment)) +
  scale_x_date(limits = c(aque_start_date, as.Date("2021-10-02"))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  geom_point(size = 2) +
  geom_line() +
  geom_vline(xintercept = ivee_after_date, show.legend = NA) +
  scale_color_manual(name = NULL,
                       breaks = c("ANNUAL", "CONTINUAL", "CONTROL"),
                       values = c("ANNUAL" = annual_col, "CONTINUAL" = continual_col, "CONTROL" = "grey")) +
    scale_shape_manual(name = NULL,
                       breaks = c("ANNUAL", "CONTINUAL", "CONTROL"),
                       values = c("ANNUAL" = annual_shape, "CONTINUAL" = continual_shape, "CONTROL" = 21)) +
  theme_bw() + 
  theme(legend.position = "none") +
  labs(title = "IVEE",
       x = "Sampling date",
       y = " ")
napl_total_frond_timeseries <- total_frond_timeseries_fxn("NAPL")

aque_total_frond_timeseries
mohk_total_frond_timeseries
ivee_total_frond_timeseries
napl_total_frond_timeseries
carp_total_frond_timeseries

# y-axis label for patchwork side eye emoji
yaxislabel <- ggplot(data.frame(l = "kelp frond density", x = 1, y = 1)) +
      geom_text(aes(x, y, label = l), angle = 90) + 
      theme_void() +
      coord_cartesian(clip = "off")

plots_together <- yaxislabel + (aque_total_frond_timeseries / mohk_total_frond_timeseries / napl_total_frond_timeseries / ivee_total_frond_timeseries / carp_total_frond_timeseries) +
  plot_layout(guides = "collect", widths = c(1, 25)) &
  theme(legend.position = "bottom")

plots_together

# ggsave(here::here("figures", "kelp_total_frond_ts-20211012.jpg"), plots_together, height = 9, width = 5, dpi = 200)
```

```{r}
kelp_timeseries_fxn <- function(site_choice) {
  after_date <- if(site_choice == "AQUE") {
    aque_after_date
  } else if(site_choice == "NAPL") {
    napl_after_date
  } else if(site_choice == "CARP") {
    carp_after_date
  } else if(site_choice == "IVEE") {
    ivee_after_date
  } else if(site_choice == "MOHK") {
    mohk_after_date
  }
  
  
  
  ggplot() +
    scale_x_date(limits = c(aque_start_date, as.Date("2021-10-02"))) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
    geom_point(data = delta_fronds %>% filter(site == site_choice & delta_annual != "NA"), 
               aes(x = date, y = delta_annual, color = "Annual")) +
    geom_line(data = delta_fronds %>% filter(site == site_choice & delta_annual != "NA"),
              aes(x = date, y = delta_annual, color = "Annual")) +
    geom_point(data = delta_fronds %>% filter(site == site_choice & delta_continual != "NA"), 
               aes(x = date, y = delta_continual, color = "Continual")) +
    geom_line(data = delta_fronds %>% filter(site == site_choice & delta_continual != "NA"),
              aes(x = date, y = delta_continual, color = "Continual")) +
    geom_vline(xintercept = after_date, show.legend = NA) +
    scale_color_manual(name = NULL,
                       breaks = c("Annual", "Continual"),
                       values = c("Annual" = "green", "Continual" = "blue")) +
    theme_bw() + 
    labs(title = site_choice,
         x = " ",
         y = " ")
}

aque_kelp_timeseries <- kelp_timeseries_fxn("AQUE")
mohk_kelp_timeseries <- kelp_timeseries_fxn("MOHK")
carp_kelp_timeseries <- kelp_timeseries_fxn("CARP")
ivee_kelp_timeseries <- ggplot() +
  scale_x_date(limits = c(aque_start_date, as.Date("2020-06-01"))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  geom_point(data = delta_fronds %>% filter(site == "IVEE" & delta_annual != "NA"), 
             aes(x = date, y = delta_annual), color = "green") +
  geom_line(data = delta_fronds %>% filter(site == "IVEE" & delta_annual != "NA"),
            aes(x = date, y = delta_annual), color = "green") +
  geom_vline(xintercept = ivee_after_date, show.legend = NA) +
  theme_bw() + 
  labs(title = "IVEE",
       x = "Sampling date",
       y = " ")
napl_kelp_timeseries <- kelp_timeseries_fxn("NAPL")

aque_kelp_timeseries
mohk_kelp_timeseries
ivee_kelp_timeseries
napl_kelp_timeseries
carp_kelp_timeseries

# y-axis label for patchwork side eye emoji
yaxislabel <- ggplot(data.frame(l = "kelp fronds (control - removal)", x = 1, y = 1)) +
      geom_text(aes(x, y, label = l), angle = 90) + 
      theme_void() +
      coord_cartesian(clip = "off")

plots_together <- yaxislabel + (aque_kelp_timeseries / mohk_kelp_timeseries / napl_kelp_timeseries / ivee_kelp_timeseries / carp_kelp_timeseries) +
  plot_layout(guides = "collect", widths = c(1, 25)) &
  theme(legend.position = "bottom")

plots_together

# ggsave(here::here("figures", "kelp_frond_ts-20211012.jpg"), plots_together, height = 9, width = 5, dpi = 200)
```

## Plotting control only
```{r}
control_fronds_plot <- ggplot(control_fronds, aes(x = date, y = total_fronds)) +
  geom_line(aes(color = site), alpha = 0.8) +
  geom_point(aes(fill = site, shape = site), size = 3) +
  scale_shape_manual(values = c(21, 22, 23, 24, 25)) +
  scale_color_manual(values = c(AQUE_col, CARP_col, IVEE_col, MOHK_col, NAPL_col)) +
  scale_fill_manual(values = c(AQUE_col, CARP_col, IVEE_col, MOHK_col, NAPL_col)) +
  theme_bw() +
  labs(x = "Sampling date",
       y = "Total fronds",
       title = "Kelp fronds") 

control_fronds_plot
```

## plotting annual and continual in panels
```{r}
ggplot(data = total_fronds %>% filter(treatment %in% c("ANNUAL", "CONTINUAL")), 
       aes(x = date, y = total_fronds)) +
  geom_point(aes(fill = site, shape = site), size = 2, alpha = 0.7) +
  geom_smooth(aes(color = site), fill = 0.8) +
  geom_vline(xintercept = ivee_after_date, show.legend = NA) + 
  scale_shape_manual(values = c(21, 22, 23, 24, 25)) +
  scale_y_continuous(limits = c(-100, 2700)) +
  # scale_color_manual(values = c(AQUE_col, CARP_col, IVEE_col, MOHK_col, NAPL_col)) +
  # scale_fill_manual(values = c(AQUE_col, CARP_col, IVEE_col, MOHK_col, NAPL_col)) +
  theme_bw() +
  labs(x = "Sampling date",
       y = "Total fronds",
       title = "Kelp fronds") +
  facet_wrap(~treatment + season, nrow = 2)

# ggsave(here::here("figures", "kelp_frond_by_site_smooth_ts-20211012.jpg"), height = 8, width = 10, dpi = 200)
```


# 2. Urchin biomass
```{r}
urchin_density <- read_csv(here::here("data", "LTE_Quad_Swath_All_Years_20200605.csv")) %>% 
  clean_names() %>% 
  # create a sample_ID for each sampling date at each treatment at each site
  unite("sample_ID", site, treatment, date, remove = FALSE) %>% 
  # change to lower case
  mutate_at(c("group", "mobility", "growth_morph"), str_to_lower) %>% 
  # make a new column designating "start", "during" and "after" removal
  mutate(exp_dates = case_when(
    site == "NAPL" & sample_ID %in% napl_start_dates ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & sample_ID %in% mohk_start_dates ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & sample_ID %in% aque_start_dates ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & sample_ID %in% carp_start_dates ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & sample_ID %in% ivee_start_dates ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  select(1:14) %>% 
  filter(sp_code %in% c("SPL", "SPS", "SFL", "SFS") & treatment == "CONTROL")

urchin_summary <- urchin_density %>% 
  group_by(sample_ID, site, date, scientific_name, sp_code) %>% 
  summarize(total_urchins = sum(count)) %>% 
  filter(total_urchins > 0) 

control_urchins_plot <- ggplot(urchin_summary %>% filter(sp_code == "SPL"), aes(x = date, y = total_urchins)) + 
  geom_line(aes(color = site), alpha = 0.8) +
  geom_point(aes(fill = site, shape = site), size = 3) +
  scale_shape_manual(values = c(21, 22, 23, 24, 25)) +
  scale_color_manual(values = c(AQUE_col, CARP_col, IVEE_col, MOHK_col, NAPL_col)) +
  scale_fill_manual(values = c(AQUE_col, CARP_col, IVEE_col, MOHK_col, NAPL_col)) +
  theme_bw() +
  labs(title = "Purple urchin density",
       x = "Sampling date",
       y = "Urchin count per transect") +
  theme(legend.position = "none")
```

# 3. Detrital biomass
```{r}
detritus <- read_csv(here::here("data", "LTE_Detritus_Biomass_All_Years_20200605.csv")) %>% 
  clean_names() %>% 
  # create a sample_ID for each sampling date at each treatment at each site
  unite("sample_ID", site, treatment, date, remove = FALSE) %>% 
  # change to lower case
  mutate_at(c("group", "mobility", "growth_morph"), str_to_lower) %>% 
  # make a new column designating "start", "during" and "after" removal
  mutate(exp_dates = case_when(
    site == "NAPL" & sample_ID %in% napl_start_dates ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & sample_ID %in% mohk_start_dates ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & sample_ID %in% aque_start_dates ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & sample_ID %in% carp_start_dates ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & sample_ID %in% ivee_start_dates ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  select(1:14) %>% 
  filter(treatment == "CONTROL")

detritus_summary <- detritus %>% 
  group_by(sample_ID, site, date, sp_code) %>% 
  summarize(total_detritus = sum(wet_wt)) %>% 
  filter(total_detritus > 0) 

control_detritus_plot <- ggplot(detritus_summary, aes(x = date, y = total_detritus)) + 
  geom_line(aes(color = site), alpha = 0.8) +
  geom_point(aes(fill = site, shape = site), size = 3) +
  scale_shape_manual(values = c(21, 22, 23, 24, 25)) +
  scale_color_manual(values = c(AQUE_col, CARP_col, IVEE_col, MOHK_col, NAPL_col)) +
  scale_fill_manual(values = c(AQUE_col, CARP_col, IVEE_col, MOHK_col, NAPL_col)) +
  theme_bw() +
  labs(title = "Detritus wet weight",
       x = "Sampling date",
       y = "Total detritus (g)") +
  theme(legend.position = "none")

control_detritus_plot

kelp_urchins_detritus <- (control_fronds_plot / control_urchins_plot / control_detritus_plot) +
  plot_layout(guides = "collect")

kelp_urchins_detritus
# ggsave(here::here("figures", "kelp_urchins_detritus.jpg"), kelp_urchins_detritus, height = 10, width = 8, dpi = 200)
```


# 4. Understory algal biomass

```{r}
# get difference in biomass between control and removal plots for each algal species
delta_algae <- biomass %>% 
  filter(group == "algae" & sp_code == "CYOS") %>% 
  # calculate total dry mass by each survey
  group_by(site, group_mobility, year, month, treatment, date, sp_code) %>% 
  summarize(total_biomass = sum(dry_gm2)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  pivot_wider(names_from = treatment, values_from = total_biomass) %>% 
  mutate(delta_annual = CONTROL - ANNUAL,
         delta_continual = CONTROL - CONTINUAL) %>% 
  # create a sample_ID for each sampling date at each site
  unite("sample_ID", site, date, remove = FALSE) %>% 
  filter(exp_dates == "after")

algae_timeseries_fxn <- function(site_choice) {
  after_date <- if(site_choice == "AQUE") {
    aque_after_date
  } else if(site_choice == "NAPL") {
    napl_after_date
  } else if(site_choice == "CARP") {
    carp_after_date
  } else if(site_choice == "IVEE") {
    ivee_after_date
  } else if(site_choice == "MOHK") {
    mohk_after_date
  }
  
  ggplot() +
    scale_x_date(limits = c(after_date, as.Date("2020-06-01"))) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
    # annual
    geom_point(data = delta_algae %>% filter(site == site_choice & delta_annual != "NA"), 
               aes(x = date, y = delta_annual, 
                   color = "Annual removal", shape = "Annual removal"), size = 3) +
    geom_line(data = delta_algae %>% filter(site == site_choice & delta_annual != "NA"),
              aes(x = date, y = delta_annual, color = "Annual removal")) +
    # continual
    geom_point(data = delta_algae %>% filter(site == site_choice & delta_continual != "NA"), 
               aes(x = date, y = delta_continual, 
                   color = "Continual removal", shape = "Continual removal"), size = 3) +
    geom_line(data = delta_algae %>% filter(site == site_choice & delta_continual != "NA"),
              aes(x = date, y = delta_continual, color = "Continual removal")) +
    geom_vline(xintercept = after_date, show.legend = NA) +
    scale_color_manual(name = NULL,
                       breaks = c("Annual removal", "Continual removal"),
                       values = c("Annual removal" = annual_col, "Continual removal" = continual_col)) +
    scale_shape_manual(name = NULL,
                       breaks = c("Annual removal", "Continual removal"),
                       values = c("Annual removal" = 19, "Continual removal" = 17)) +
    theme_bw() + 
    labs(title = site_choice,
         x = " ",
         y = " ")
}

aque_algae_timeseries <- algae_timeseries_fxn("AQUE")
mohk_algae_timeseries <- algae_timeseries_fxn("MOHK")
ivee_algae_timeseries <- ggplot(delta_algae %>% filter(site == "IVEE" & delta_annual != "NA"), aes(x = date, y = delta_annual)) +
  scale_x_date(limits = c(ivee_after_date, as.Date("2020-06-01"))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  geom_point(shape = annual_shape, size = 3, color = annual_col) +
  geom_line(color = annual_col) +
  geom_vline(xintercept = ivee_after_date, show.legend = NA) +
  theme_bw() + 
  labs(title = "IVEE",
       x = "Sampling date",
       y = " ")
napl_algae_timeseries <- algae_timeseries_fxn("NAPL")
carp_algae_timeseries <- algae_timeseries_fxn("CARP")

# y-axis label for patchwork side eye emoji
yaxislabel <- ggplot(data.frame(l = "algal biomass (control - removal)", x = 1, y = 1)) +
      geom_text(aes(x, y, label = l), angle = 90) + 
      theme_void() +
      coord_cartesian(clip = "off")

plots_together <- yaxislabel + (aque_algae_timeseries / mohk_algae_timeseries / napl_algae_timeseries / carp_algae_timeseries / ivee_algae_timeseries) +
  plot_layout(guides = "collect", widths = c(1, 25)) &
  theme(legend.position = "bottom")

plots_together

# ggsave(here::here("figures", "algae_biomass_ts-CYOS-after.jpg"), plots_together, height = 9, width = 8, dpi = 200)

delta_annual_timeseries <- ggplot(delta_algae %>% filter(delta_annual != "NA"), 
                                  aes(x = date, y = delta_annual)) +
  scale_x_date(limits = c(ivee_after_date, as.Date("2020-06-01"))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  
  geom_point(shape = annual_shape, size = 2) +
  # geom_line() +
  geom_vline(xintercept = ivee_after_date, show.legend = NA) +
  geom_smooth(method = "lm", color = annual_col, size = 3) +
  theme_bw() + 
  theme(legend.position = "bottom") +
  labs(title = "Annual",
       x = "Sampling date",
       y = expression(Delta~"Biomass (dry g/"~m^2~") (control - removal)"))

delta_continual_timeseries <- ggplot(delta_algae %>% filter(delta_continual != "NA"), 
                                  aes(x = date, y = delta_continual)) +
  scale_x_date(limits = c(ivee_after_date, as.Date("2020-06-01"))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  
  geom_point(shape = continual_shape, size = 2) +
  # geom_line() +
  geom_smooth(method = "lm", size = 3, color = continual_col) +
  geom_vline(xintercept = ivee_after_date, show.legend = NA) +
  # scale_color_manual(values = c(AQUE_col, CARP_col, MOHK_col, NAPL_col)) +
  theme_bw() + 
  theme(legend.position = "none") +
  labs(title = "Continual",
       x = "Sampling date",
       y = expression(Delta~"Biomass (dry g/"~m^2~") (control - removal)"))

plots_together <- (delta_annual_timeseries + delta_continual_timeseries)
plots_together

# ggsave(here::here("figures", "delta_biomass.jpg"), plots_together, width = 8, height = 4, dpi = 150)
  
```

```{r}
delta_algae_all <- biomass %>% 
  filter(sp_code %in% common_algae) %>% 
  # calculate total dry mass by each survey
  group_by(site, group_mobility, year, month, treatment, date) %>% 
  summarize(total_biomass = sum(dry_gm2)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  pivot_wider(names_from = treatment, values_from = total_biomass) %>% 
  mutate(delta_annual = CONTROL - ANNUAL,
         delta_continual = CONTROL - CONTINUAL) %>% 
  # create a sample_ID for each sampling date at each site
  unite("sample_ID", site, date, remove = FALSE) %>% 
  full_join(., site_quality, by = "site")

delta_algae_spp <- biomass %>% 
  filter(sp_code %in% common_algae) %>% 
  # calculate total dry mass by each survey
  group_by(site, group_mobility, year, month, treatment, date, scientific_name) %>% 
  summarize(total_biomass = sum(dry_gm2)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after"))) %>% 
  pivot_wider(names_from = treatment, values_from = total_biomass) %>% 
  mutate(delta_annual = CONTROL - ANNUAL,
         delta_continual = CONTROL - CONTINUAL) %>% 
  # create a sample_ID for each sampling date at each site
  unite("sample_ID", site, date, remove = FALSE) %>% 
  # filter(exp_dates == "after") %>% 
  arrange(scientific_name) %>% 
  # replace space in scientific name with underscore
  mutate(scientific_name = str_replace(scientific_name, " ", "_")) %>% 
  fuzzy_full_join(., traits, by = "scientific_name", match_fun = str_detect) %>% 
  drop_na(sample_ID, taxon_phylum) %>% 
  full_join(., site_quality, by = "site")

delta_annual_timeseries_all <- ggplot(delta_algae_all %>% filter(delta_annual != "NA" & exp_dates == "after"), 
                                  aes(x = date, y = delta_annual)) +
  # scale_x_date(limits = c(ivee_after_date, as.Date("2020-06-01"))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  geom_point(shape = annual_shape) +
  # geom_line() +
  geom_vline(xintercept = ivee_after_date, show.legend = NA) +
  geom_smooth(method = "lm", color = annual_col, size = 2) +
  theme_bw() + 
  theme(legend.position = "none", 
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Annual",
       x = "Sampling date",
       y = expression(Delta~"Biomass (dry g/"~m^2~") (control - removal)")) +
  facet_wrap(~quality)

delta_continual_timeseries_all <- ggplot(delta_algae_all %>% filter(delta_continual != "NA" & exp_dates == "after"), 
                                  aes(x = date, y = delta_continual)) +
  scale_x_date(limits = c(ivee_after_date, as.Date("2020-06-01"))) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  
  geom_point(shape = continual_shape) +
  geom_smooth(method = "lm", size = 2, color = continual_col) +
  geom_vline(xintercept = ivee_after_date, show.legend = NA) +
  # scale_color_manual(values = c(AQUE_col, CARP_col, MOHK_col, NAPL_col)) +
  theme_bw() + 
  theme(legend.position = "none", 
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Continual",
       x = "Sampling date",
       y = expression(Delta~"Biomass (dry g/"~m^2~") (control - removal)")) +
  facet_wrap(~quality)

plots_together <- delta_annual_timeseries_all + delta_continual_timeseries_all

# ggsave(here::here("figures", "delta_biomass_all-2021-09-06.jpg"), plots_together, width = 10, height = 4, dpi = 150)

delta_continual_timeseries_bygroup <- ggplot(delta_algae_spp %>% filter(delta_continual != "NA" & exp_dates == "after"), aes(x = date, y = delta_continual)) +
  # horizontal line at 0
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  # vertical line when experiment ends
  geom_vline(xintercept = ivee_after_date, show.legend = NA) +
  # points
  geom_point(shape = continual_shape) +
  geom_smooth(aes(color = growth_form), method = "lm", size = 2, alpha = 0.7) +
  scale_color_manual(values = cal_palette("kelp1")) +
  theme_bw() +
  labs(title = "Continual",
       x = "Sampling date",
       y = expression(Delta~"Biomass (dry g/"~m^2~") (control - removal)")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom") +
  guides(color = guide_legend(ncol = 3)) +
  facet_grid(~ quality)

# ggsave(here::here("figures", "delta_biomass_bygroup_continual-2021-09-06.jpg"), delta_continual_timeseries_bygroup, width = 9, height = 10, dpi = 150)

delta_annual_timeseries_bygroup <- ggplot(delta_algae_spp %>% filter(delta_annual != "NA" & exp_dates == "after"), aes(x = date, y = delta_annual)) +
  # horizontal line at 0
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey") +
  # vertical line when experiment ends
  geom_vline(xintercept = ivee_after_date, show.legend = NA) +
  # points
  geom_point(shape = annual_shape) +
  geom_smooth(aes(color = growth_form), method = "lm", size = 2, alpha = 0.7) +
  scale_color_manual(values = cal_palette("kelp1")) +
  theme_bw() +
  labs(title = "Annual",
       x = "Sampling date",
       y = expression(Delta~"Biomass (dry g/"~m^2~") (control - removal)")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom") +
  guides(color = guide_legend(ncol = 3)) +
  facet_grid(~ quality)

# ggsave(here::here("figures", "delta_biomass_bygroup_annual-2021-09-06.jpg"), delta_annual_timeseries_bygroup, width = 9, height = 10, dpi = 150)

plots_together <- (delta_annual_timeseries_bygroup + delta_continual_timeseries_bygroup) +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")

# ggsave(here::here("figures", "delta_biomass_bygroup-2021-09-06.jpg"), plots_together, width = 10, height = 4, dpi = 150)

```

```{r}
algae_all_biomass <- biomass %>% 
  filter(sp_code %in% common_algae) %>% 
  # calculate total dry mass by each survey
  group_by(site, year, month, treatment, date) %>% 
  summarize(total_biomass = sum(dry_gm2)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after")),
  season = case_when(
    month %in% c(12, 1, 2) ~ "winter",
    month %in% c(3, 4, 5) ~ "spring",
    month %in% c (6, 7, 8) ~ "summer",
    month %in% c(9, 10, 11) ~ "fall"
    ),
  season = fct_relevel(season, "winter", "spring", "summer", "fall")) %>% 
  pivot_longer(col = total_biomass, names_to = "measurement", values_to = "value")

total_fronds_fig <- total_fronds %>% 
  pivot_longer(col = total_fronds, names_to = "measurement", values_to = "value")

df_fig <- rbind(total_fronds_fig, algae_all_biomass) %>% 
  arrange(date) %>% 
  mutate(measurement = fct_relevel(measurement, c("total_fronds", "total_biomass"))) %>% 
  filter(treatment %in% c("ANNUAL", "CONTROL"))


ggplot(algae_all_biomass, aes(x = date, y = total_biomass, color = site)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  labs(x = "Date", 
       y = "Dry weight density (g/m^2)",
       title = "Understory algal biomass") +
  facet_wrap(~treatment)

# ggsave(here::here("figures", "biomass_all-2021-11-02.jpg"), width = 10, height = 4, dpi = 150)
  
```

```{r}
test_fig_under <- ggplot(data = df_fig, # CHANGE
                         aes(x = date, y = value, 
                             color = measurement, alpha = treatment, shape = measurement)) +
  geom_point(size = 2) +
  geom_line(size = 1) +
  scale_alpha_manual(values = c("ANNUAL" = 1, "CONTROL" = 0.4)) +
  scale_color_manual(values = c(total_fronds = kelp_col, total_biomass = under_col)) +
  scale_shape_manual(values = c("total_fronds" = 19, "total_biomass" = 17)) +
  # CHANGE
  geom_vline(aes(xintercept = carp_after_date)) +
  theme_minimal() +
  facet_wrap(vars(measurement, site), nrow = 2, scales = "free_y",
             labeller = labeller(measurement = c(total_fronds = "Total fronds", total_biomass = "Total understory algal biomass"))) +
  theme(legend.position = "none") +
  labs(x = "Date",
       y = "")

test_fig_under

# CHANGE
ggsave(here::here("figures/timeseries", "timeseries-all_panels-annual.jpg"), width = 25, height = 10, dpi = 150)
```

```{r}
algae_spp_biomass <- biomass %>% 
  # filter(sp_code %in% common_algae) %>% 
  filter(group == "algae" & sp_code != "MAPY") %>% 
  # calculate total dry mass by each survey
  group_by(site, year, month, treatment, date, sp_code) %>% 
  summarize(total_biomass = sum(dry_gm2)) %>% 
  ungroup() %>% 
  # add new column with start/during/after
  mutate(exp_dates = case_when(
    site == "NAPL" & date == napl_start_date ~ "start",
    site == "NAPL" & date > napl_after_date ~ "after",
    site == "MOHK" & date == mohk_start_date ~ "start",
    site == "MOHK" & date > mohk_after_date ~ "after",
    site == "AQUE" & date == aque_start_date ~ "start",
    site == "AQUE" & date > aque_after_date ~ "after",
    site == "CARP" & date == carp_start_date ~ "start",
    site == "CARP" & date > carp_after_date ~ "after",
    site == "IVEE" & date == ivee_start_date ~ "start",
    site == "IVEE" & date > ivee_after_date ~ "after",
    TRUE ~ "during"
  ),
  exp_dates = factor(exp_dates, levels = c("start", "during", "after")),
  season = case_when(
    month %in% c(12, 1, 2) ~ "winter",
    month %in% c(3, 4, 5) ~ "spring",
    month %in% c (6, 7, 8) ~ "summer",
    month %in% c(9, 10, 11) ~ "fall"
    ),
  season = fct_relevel(season, "winter", "spring", "summer", "fall")) %>% 
  pivot_longer(col = total_biomass, names_to = "measurement", values_to = "value") %>% 
  rbind(., mutate(total_fronds_fig, sp_code = "MAPY")) %>% 
  # filter(treatment %in% c("CONTROL", "CONTINUAL")) %>% 
  mutate(measurement = fct_relevel(measurement, c("total_fronds", "total_biomass")))

understory_fig_df <- algae_spp_biomass %>% 
  filter(site == "AQUE" & sp_code %in% c("DL", "MAPY") & treatment %in% c("CONTROL", "CONTINUAL"))

test_fig_under <- ggplot(data = understory_fig_df,
                         aes(x = date, y = value, 
                             color = sp_code, alpha = treatment, shape = sp_code)) +
  geom_point(size = 2) +
  geom_line(size = 1) +
  scale_alpha_manual(values = c("ANNUAL" = 1, "CONTROL" = 0.4)) +
  scale_color_manual(values = c("MAPY" = kelp_col, "DL" = under_col)) +
  scale_shape_manual(values = c("MAPY" = 19, "DL" = 17)) +
  # CHANGE
  geom_vline(aes(xintercept = aque_after_date)) +
  theme_minimal() +
  facet_wrap(~measurement, nrow = 2, scales = "free_y", strip.position = "left",
             labeller = labeller(measurement = c(total_fronds = "Total fronds", total_biomass = "Total Desmarestia biomass"))) +
  theme(legend.position = "none") +
  labs(x = "Date",
       y = "",
       # CHANGE
       title = "Arroyo Quemado")

test_fig_under

# CHANGE
ggsave(here::here("figures/timeseries", "timeseries-aque-dl.jpg"), width = 9, height = 10, dpi = 150)
```

```{r}
other_df_fig <- rbind(total_fronds_fig, algae_all_biomass) %>% 
  arrange(date) %>% 
  mutate(measurement = fct_relevel(measurement, c("total_fronds", "total_biomass"))) %>% 
  ungroup() %>% 
  group_by(year, treatment, season, measurement) %>% 
 # summarize(mean = mean(value))
  mutate(mean_value = mean(value),
         sd_value = sd(value)) %>% 
  select(treatment, date, measurement, mean_value, sd_value) %>% 
  filter(treatment %in% c("CONTINUAL", "CONTROL"))

ggplot(data = other_df_fig %>% filter(treatment == "CONTROL"), aes(x = date, y = mean_value, 
                                color = measurement, alpha = treatment, shape = measurement)) +
  geom_point(size = 2) +
  geom_line(size = 1) +
  geom_vline(aes(xintercept = as_date("2016-01-01"))) +
  scale_alpha_manual(values = c("CONTINUAL" = 1, "CONTROL" = 0.3)) +
  scale_color_manual(values = c(total_fronds = kelp_col, total_biomass = under_col)) +
  scale_shape_manual(values = c("total_fronds" = 19, "total_biomass" = 17)) +
  theme_minimal() +
  theme(legend.position = "none") +
  facet_wrap(~measurement, nrow = 2, scales = "free_y", strip.position = "left",
             labeller = labeller(measurement = c(total_fronds = "Mean fronds", total_biomass = "Mean understory biomass"))) +
  labs(x = "Date",
        y = "", 
        title = "Mean kelp fronds/understory biomass across sites - CONTROL")

# CHANGE
ggsave(here::here("figures/timeseries", "timeseries-all_averaged-control.jpg"), width = 9, height = 10, dpi = 150)
```



